// Types
export interface Price {
    amount: number
    currency: string
  }
  
  export interface ElectronicsVendor {
    id: string
    name: string
    logo: string
    category: "smartphones" | "computers" | "audio" | "appliances" | "gaming"
    description: string
    rating: number
    reviewCount: number
    location: string
    contact: {
      phone: string
      email: string
      website: string
    }
    openingHours: string
    products: ElectronicsProduct[]
    amenities: string[]
    images: string[]
    established?: number
    brands?: string[]
  }
  
  export interface ElectronicsProduct {
    id: string
    name: string
    description: string
    price: Price
    image: string
    isPopular?: boolean
    isNew?: boolean
    isDiscount?: boolean
    discountPercentage?: number
    category: string
    tags: string[]
    specifications?: Record<string, string | number | boolean>
    warranty?: string
    stock?: number
    colors?: string[]
    releaseDate?: string
  }
  
  // Helper function to format price
  export const formatPrice = (price: Price): string => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: price.currency,
      maximumFractionDigits: 0,
    }).format(price.amount)
  }
  
  // Mock data for electronics vendors
  export const electronicsVendors: ElectronicsVendor[] = [
    // Smartphone Vendors
    {
      id: "tech-hub",
      name: "Tech Hub",
      logo: "/placeholder.svg?height=80&width=80",
      category: "smartphones",
      description:
        "Premier destination for the latest smartphones and mobile accessories with expert service and competitive prices.",
      rating: 4.8,
      reviewCount: 356,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 712 345 678",
        email: "info@techhub.co.ke",
        website: "www.techhub.co.ke",
      },
      openingHours: "Mon-Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 6:00 PM",
      amenities: ["Free Wi-Fi", "Device Testing", "Repair Services", "Trade-In", "Express Delivery"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2012,
      brands: ["Apple", "Samsung", "Google", "Xiaomi", "Oppo", "Huawei"],
      products: [
        {
          id: "iphone-15-pro",
          name: "iPhone 15 Pro Max - 256GB",
          description:
            "Apple's flagship smartphone with A17 Pro chip, titanium design, and a groundbreaking camera system for exceptional photos and videos.",
          price: { amount: 210000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Smartphones",
          tags: ["Apple", "Premium", "5G", "iOS"],
          specifications: {
            display: "6.7-inch Super Retina XDR, ProMotion",
            processor: "A17 Pro",
            ram: "8GB",
            storage: "256GB",
            camera: "48MP main + 12MP ultrawide + 12MP telephoto",
            battery: "4422mAh",
            os: "iOS 17",
          },
          warranty: "1 year manufacturer warranty",
          stock: 15,
          colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
          releaseDate: "2023-09-22",
        },
        {
          id: "samsung-s23-ultra",
          name: "Samsung Galaxy S23 Ultra - 512GB",
          description:
            "Experience the ultimate smartphone with the Galaxy S23 Ultra featuring a 200MP camera, S Pen, and powerful Snapdragon processor.",
          price: { amount: 180000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Smartphones",
          tags: ["Samsung", "Premium", "5G", "Android"],
          specifications: {
            display: "6.8-inch Dynamic AMOLED 2X, 120Hz",
            processor: "Snapdragon 8 Gen 2",
            ram: "12GB",
            storage: "512GB",
            camera: "200MP main + 12MP ultrawide + 10MP telephoto + 10MP telephoto",
            battery: "5000mAh",
            os: "Android 13",
          },
          warranty: "2 year manufacturer warranty",
          stock: 8,
          colors: ["Phantom Black", "Cream", "Green", "Lavender"],
          releaseDate: "2023-02-17",
        },
        {
          id: "google-pixel-8",
          name: "Google Pixel 8 Pro - 128GB",
          description:
            "Google's most advanced Pixel phone with the new Tensor G3 chip, incredible AI features, and a stunning camera system.",
          price: { amount: 140000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Smartphones",
          tags: ["Google", "Premium", "5G", "Android"],
          specifications: {
            display: "6.7-inch LTPO OLED, 120Hz",
            processor: "Google Tensor G3",
            ram: "12GB",
            storage: "128GB",
            camera: "50MP main + 48MP ultrawide + 48MP telephoto",
            battery: "5050mAh",
            os: "Android 14",
          },
          warranty: "2 year manufacturer warranty",
          stock: 12,
          colors: ["Obsidian", "Porcelain", "Bay"],
          releaseDate: "2023-10-12",
        },
        {
          id: "xiaomi-13t-pro",
          name: "Xiaomi 13T Pro - 256GB",
          description:
            "Flagship performance at a competitive price with Leica optics, MediaTek Dimensity 9200+ chip, and ultra-fast charging.",
          price: { amount: 95000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 15,
          category: "Smartphones",
          tags: ["Xiaomi", "Mid-range", "5G", "Android"],
          specifications: {
            display: "6.67-inch AMOLED, 144Hz",
            processor: "MediaTek Dimensity 9200+",
            ram: "12GB",
            storage: "256GB",
            camera: "50MP main + 12MP ultrawide + 50MP telephoto",
            battery: "5000mAh",
            os: "Android 13, MIUI 14",
          },
          warranty: "1 year manufacturer warranty",
          stock: 20,
          colors: ["Black", "Blue", "Green"],
          releaseDate: "2023-09-26",
        },
      ],
    },
    {
      id: "mobile-zone",
      name: "Mobile Zone",
      logo: "/placeholder.svg?height=80&width=80",
      category: "smartphones",
      description:
        "Specialized in budget and mid-range smartphones with excellent value, offering a wide selection of brands and accessories.",
      rating: 4.6,
      reviewCount: 289,
      location: "Mombasa, Kenya",
      contact: {
        phone: "+254 723 456 789",
        email: "sales@mobilezone.co.ke",
        website: "www.mobilezone.co.ke",
      },
      openingHours: "Mon-Sun: 8:00 AM - 9:00 PM",
      amenities: ["Screen Protector Installation", "Phone Cases", "Repair Services", "Financing Options", "Trade-In"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2015,
      brands: ["Xiaomi", "Oppo", "Realme", "Tecno", "Infinix", "Nokia"],
      products: [
        {
          id: "tecno-camon-20",
          name: "Tecno Camon 20 Premier - 256GB",
          description:
            "Feature-packed smartphone with a 108MP camera, large display, and long-lasting battery at an affordable price.",
          price: { amount: 45000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Smartphones",
          tags: ["Tecno", "Budget", "4G", "Android"],
          specifications: {
            display: "6.67-inch AMOLED, 120Hz",
            processor: "MediaTek Helio G99",
            ram: "8GB",
            storage: "256GB",
            camera: "108MP main + 2MP depth + 2MP macro",
            battery: "5000mAh",
            os: "Android 13, HiOS 13",
          },
          warranty: "1 year manufacturer warranty",
          stock: 35,
          colors: ["Black", "Blue", "Silver"],
          releaseDate: "2023-05-15",
        },
        {
          id: "infinix-note-30",
          name: "Infinix Note 30 Pro - 128GB",
          description:
            "Powerful mid-range smartphone with fast charging, stereo speakers, and a versatile camera system.",
          price: { amount: 35000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 20,
          category: "Smartphones",
          tags: ["Infinix", "Budget", "4G", "Android"],
          specifications: {
            display: "6.78-inch AMOLED, 120Hz",
            processor: "MediaTek Helio G99",
            ram: "8GB",
            storage: "128GB",
            camera: "108MP main + 2MP depth + 2MP macro",
            battery: "5000mAh",
            os: "Android 13, XOS 13",
          },
          warranty: "1 year manufacturer warranty",
          stock: 42,
          colors: ["Magic Black", "Sunset Gold", "Variable Gold"],
          releaseDate: "2023-05-22",
        },
        {
          id: "xiaomi-redmi-note-12",
          name: "Xiaomi Redmi Note 12 - 128GB",
          description:
            "Feature-rich budget smartphone with AMOLED display, decent performance, and excellent battery life.",
          price: { amount: 25000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Smartphones",
          tags: ["Xiaomi", "Budget", "4G", "Android"],
          specifications: {
            display: "6.67-inch AMOLED, 120Hz",
            processor: "Snapdragon 685",
            ram: "6GB",
            storage: "128GB",
            camera: "50MP main + 8MP ultrawide + 2MP macro",
            battery: "5000mAh",
            os: "Android 13, MIUI 14",
          },
          warranty: "1 year manufacturer warranty",
          stock: 50,
          colors: ["Onyx Gray", "Ice Blue", "Mint Green"],
          releaseDate: "2023-03-23",
        },
        {
          id: "nokia-g42",
          name: "Nokia G42 5G - 128GB",
          description: "Durable and reliable 5G smartphone with clean Android experience and excellent repairability.",
          price: { amount: 30000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Smartphones",
          tags: ["Nokia", "Budget", "5G", "Android"],
          specifications: {
            display: "6.56-inch LCD, 90Hz",
            processor: "Snapdragon 480+ 5G",
            ram: "6GB",
            storage: "128GB",
            camera: "50MP main + 2MP depth + 2MP macro",
            battery: "5000mAh",
            os: "Android 13",
          },
          warranty: "2 year manufacturer warranty",
          stock: 28,
          colors: ["So Purple", "So Grey", "So Pink"],
          releaseDate: "2023-07-18",
        },
      ],
    },
  
    // Computer Vendors
    {
      id: "computer-world",
      name: "Computer World",
      logo: "/placeholder.svg?height=80&width=80",
      category: "computers",
      description:
        "Premium computer retailer offering the latest laptops, desktops, and accessories with expert advice and after-sales support.",
      rating: 4.9,
      reviewCount: 412,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 734 567 890",
        email: "info@computerworld.co.ke",
        website: "www.computerworld.co.ke",
      },
      openingHours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 5:00 PM, Closed on Sundays",
      amenities: ["Technical Support", "Custom PC Building", "Business Solutions", "Financing", "Extended Warranty"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2008,
      brands: ["Apple", "Dell", "HP", "Lenovo", "Asus", "Microsoft"],
      products: [
        {
          id: "macbook-pro-m3",
          name: 'MacBook Pro 16" M3 Pro - 32GB RAM, 1TB SSD',
          description:
            "The most powerful MacBook Pro ever with the blazing-fast M3 Pro chip, stunning Liquid Retina XDR display, and exceptional battery life.",
          price: { amount: 380000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Laptops",
          tags: ["Apple", "Premium", "macOS", "Professional"],
          specifications: {
            processor: "Apple M3 Pro (12-core CPU, 18-core GPU)",
            ram: "32GB unified memory",
            storage: "1TB SSD",
            display: "16.2-inch Liquid Retina XDR, 3456 x 2234, 120Hz",
            graphics: "18-core integrated GPU",
            battery: "Up to 22 hours",
            ports: "3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm headphone",
            weight: "2.15kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 10,
          colors: ["Space Black", "Silver"],
          releaseDate: "2023-11-07",
        },
        {
          id: "dell-xps-15",
          name: "Dell XPS 15 - Intel Core i9, 32GB RAM, 1TB SSD, RTX 4070",
          description:
            "Premium Windows laptop with stunning display, powerful performance, and excellent build quality for professionals and creators.",
          price: { amount: 280000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Laptops",
          tags: ["Dell", "Premium", "Windows", "Professional"],
          specifications: {
            processor: "Intel Core i9-13900H",
            ram: "32GB DDR5",
            storage: "1TB NVMe SSD",
            display: "15.6-inch 4K OLED, 3840 x 2400, touch",
            graphics: "NVIDIA GeForce RTX 4070 8GB",
            battery: "Up to 12 hours",
            ports: "2x Thunderbolt 4, USB-C 3.2, SD card reader, 3.5mm headphone",
            weight: "1.92kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 8,
          colors: ["Platinum Silver with Black Carbon Fiber"],
          releaseDate: "2023-05-11",
        },
        {
          id: "hp-spectre-x360",
          name: 'HP Spectre x360 14" - Intel Core i7, 16GB RAM, 1TB SSD',
          description:
            "Versatile 2-in-1 laptop with premium design, OLED display, and excellent performance for productivity and creativity.",
          price: { amount: 220000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Laptops",
          tags: ["HP", "Premium", "Windows", "2-in-1"],
          specifications: {
            processor: "Intel Core i7-1355U",
            ram: "16GB LPDDR5",
            storage: "1TB NVMe SSD",
            display: "14-inch 3K OLED, 3000 x 2000, touch",
            graphics: "Intel Iris Xe",
            battery: "Up to 15 hours",
            ports: "2x Thunderbolt 4, USB-A, microSD card reader, 3.5mm headphone",
            weight: "1.36kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 12,
          colors: ["Nightfall Black", "Nocturne Blue", "Natural Silver"],
          releaseDate: "2023-08-22",
        },
        {
          id: "lenovo-thinkpad-x1",
          name: "Lenovo ThinkPad X1 Carbon Gen 11 - Intel Core i7, 16GB RAM, 512GB SSD",
          description:
            "Business-class laptop with legendary durability, excellent keyboard, and enterprise security features.",
          price: { amount: 240000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 12,
          category: "Laptops",
          tags: ["Lenovo", "Business", "Windows", "Professional"],
          specifications: {
            processor: "Intel Core i7-1365U vPro",
            ram: "16GB LPDDR5",
            storage: "512GB NVMe SSD",
            display: "14-inch 2.8K OLED, 2880 x 1800",
            graphics: "Intel Iris Xe",
            battery: "Up to 15 hours",
            ports: "2x Thunderbolt 4, 2x USB-A, HDMI, 3.5mm headphone",
            weight: "1.12kg",
          },
          warranty: "3 year manufacturer warranty",
          stock: 15,
          colors: ["Deep Black"],
          releaseDate: "2023-04-18",
        },
      ],
    },
    {
      id: "pc-express",
      name: "PC Express",
      logo: "/placeholder.svg?height=80&width=80",
      category: "computers",
      description:
        "Specialized in gaming PCs, custom builds, and high-performance computing solutions with expert technical support.",
      rating: 4.7,
      reviewCount: 325,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 745 678 901",
        email: "sales@pcexpress.co.ke",
        website: "www.pcexpress.co.ke",
      },
      openingHours: "Mon-Sat: 9:00 AM - 7:00 PM, Sun: 11:00 AM - 5:00 PM",
      amenities: ["Custom PC Building", "Gaming Zone", "Component Testing", "Overclocking Services", "LAN Events"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2013,
      brands: ["Asus", "MSI", "Gigabyte", "Corsair", "NZXT", "AMD", "Intel", "NVIDIA"],
      products: [
        {
          id: "gaming-pc-rtx4080",
          name: "Titan X Gaming PC - RTX 4080, Ryzen 9 7950X",
          description:
            "High-end custom gaming PC with top-tier components for ultimate gaming performance and content creation.",
          price: { amount: 420000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Desktop PCs",
          tags: ["Gaming", "Custom PC", "High-end", "Windows"],
          specifications: {
            processor: "AMD Ryzen 9 7950X (16-core, 32-thread)",
            ram: "64GB DDR5-6000",
            storage: "2TB NVMe SSD + 4TB HDD",
            graphics: "NVIDIA GeForce RTX 4080 16GB",
            motherboard: "ASUS ROG X670E Hero",
            cooling: "360mm AIO Liquid Cooler",
            psu: "1000W 80+ Platinum",
            case: "NZXT H7 Flow",
          },
          warranty: "3 year warranty with lifetime support",
          stock: 5,
          colors: ["Black", "White"],
          releaseDate: "2023-09-01",
        },
        {
          id: "gaming-laptop-asus",
          name: "ASUS ROG Strix G17 - RTX 4070, Ryzen 9 7945HX",
          description:
            "Powerful gaming laptop with high refresh rate display, advanced cooling, and premium gaming features.",
          price: { amount: 320000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Gaming Laptops",
          tags: ["ASUS", "Gaming", "Windows", "High-end"],
          specifications: {
            processor: "AMD Ryzen 9 7945HX",
            ram: "32GB DDR5",
            storage: "1TB NVMe SSD",
            display: "17.3-inch QHD, 240Hz",
            graphics: "NVIDIA GeForce RTX 4070 8GB",
            battery: "Up to 6 hours gaming",
            ports: "2x USB-C, 2x USB-A, HDMI, Ethernet, 3.5mm headphone",
            weight: "2.8kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 8,
          colors: ["Eclipse Gray", "Electro Punk"],
          releaseDate: "2023-06-13",
        },
        {
          id: "workstation-pc",
          name: "ProStation X - Threadripper, RTX 4000 Ada",
          description:
            "Professional workstation designed for 3D rendering, video editing, and other demanding creative workflows.",
          price: { amount: 580000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Workstations",
          tags: ["Workstation", "Professional", "Windows", "High-end"],
          specifications: {
            processor: "AMD Threadripper PRO 5975WX (32-core, 64-thread)",
            ram: "128GB DDR4 ECC",
            storage: "4TB NVMe SSD + 16TB HDD RAID",
            graphics: "NVIDIA RTX 4000 Ada 20GB",
            motherboard: "ASUS Pro WS WRX80E-SAGE",
            cooling: "Custom Loop Liquid Cooling",
            psu: "1600W 80+ Titanium",
            case: "Fractal Design Define 7 XL",
          },
          warranty: "3 year warranty with priority support",
          stock: 3,
          colors: ["Black"],
          releaseDate: "2023-07-15",
        },
        {
          id: "mini-pc-intel",
          name: "Intel NUC 13 Pro - Core i7, 16GB RAM, 512GB SSD",
          description: "Compact yet powerful mini PC for productivity, home entertainment, and light content creation.",
          price: { amount: 120000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 15,
          category: "Mini PCs",
          tags: ["Intel", "Compact", "Windows", "Productivity"],
          specifications: {
            processor: "Intel Core i7-1360P",
            ram: "16GB DDR4",
            storage: "512GB NVMe SSD",
            graphics: "Intel Iris Xe",
            ports: "2x Thunderbolt 4, 3x USB-A, HDMI, Ethernet, 3.5mm headphone",
            dimensions: "117 x 112 x 54 mm",
            weight: "0.7kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 15,
          colors: ["Black"],
          releaseDate: "2023-03-28",
        },
      ],
    },
  
    // Audio Vendors
    {
      id: "sound-studio",
      name: "Sound Studio",
      logo: "/placeholder.svg?height=80&width=80",
      category: "audio",
      description:
        "Premium audio retailer specializing in high-fidelity speakers, headphones, and home audio systems with expert advice.",
      rating: 4.8,
      reviewCount: 278,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 756 789 012",
        email: "info@soundstudio.co.ke",
        website: "www.soundstudio.co.ke",
      },
      openingHours: "Mon-Fri: 10:00 AM - 7:00 PM, Sat: 10:00 AM - 6:00 PM, Closed on Sundays",
      amenities: ["Listening Rooms", "Home Theater Design", "Installation Services", "Acoustic Treatment", "Trade-In"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2010,
      brands: ["Sony", "Bose", "Sonos", "JBL", "Sennheiser", "Bang & Olufsen"],
      products: [
        {
          id: "sony-wh1000xm5",
          name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
          description: "Industry-leading noise cancellation with exceptional sound quality, comfort, and battery life.",
          price: { amount: 45000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Headphones",
          tags: ["Sony", "Wireless", "Noise Cancelling", "Premium"],
          specifications: {
            type: "Over-ear",
            driver: "30mm",
            frequency: "4Hz-40,000Hz",
            battery: "Up to 30 hours",
            connectivity: "Bluetooth 5.2, 3.5mm",
            features: "Adaptive noise cancellation, LDAC, multipoint connection",
            weight: "250g",
          },
          warranty: "1 year manufacturer warranty",
          stock: 20,
          colors: ["Black", "Silver"],
          releaseDate: "2022-05-20",
        },
        {
          id: "bose-700",
          name: "Bose Noise Cancelling Headphones 700",
          description: "Premium headphones with adjustable noise cancellation, crystal clear calls, and balanced sound.",
          price: { amount: 42000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Headphones",
          tags: ["Bose", "Wireless", "Noise Cancelling", "Premium"],
          specifications: {
            type: "Over-ear",
            driver: "Custom",
            frequency: "Not specified",
            battery: "Up to 20 hours",
            connectivity: "Bluetooth 5.0, 3.5mm",
            features: "11 levels of noise cancellation, touch controls, voice assistants",
            weight: "254g",
          },
          warranty: "1 year manufacturer warranty",
          stock: 15,
          colors: ["Black", "Silver", "Soapstone"],
          releaseDate: "2019-06-30",
        },
        {
          id: "sonos-era-300",
          name: "Sonos Era 300 Wireless Speaker",
          description:
            "Spatial audio speaker with room-filling sound, Dolby Atmos support, and seamless multi-room capability.",
          price: { amount: 65000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Speakers",
          tags: ["Sonos", "Wireless", "Smart Speaker", "Premium"],
          specifications: {
            drivers: "Six class-D digital amplifiers, four tweeters, two woofers",
            frequency: "Not specified",
            connectivity: "Wi-Fi 6, Bluetooth 5.0, AirPlay 2, Ethernet",
            features: "Dolby Atmos, Spatial Audio, Trueplay tuning, voice control",
            dimensions: "160 x 260 x 185 mm",
            weight: "4.47kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 10,
          colors: ["Black", "White"],
          releaseDate: "2023-03-28",
        },
        {
          id: "jbl-flip-6",
          name: "JBL Flip 6 Portable Bluetooth Speaker",
          description:
            "Rugged, waterproof portable speaker with powerful sound, deep bass, and long battery life for outdoor adventures.",
          price: { amount: 18000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 20,
          category: "Portable Speakers",
          tags: ["JBL", "Wireless", "Waterproof", "Portable"],
          specifications: {
            drivers: "Racetrack-shaped woofer, separate tweeter",
            frequency: "65Hz-20,000Hz",
            battery: "Up to 12 hours",
            connectivity: "Bluetooth 5.1",
            features: "IP67 waterproof and dustproof, PartyBoost for multiple speakers",
            dimensions: "178 x 68 x 72 mm",
            weight: "0.55kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 30,
          colors: ["Black", "Blue", "Red", "Teal", "Grey"],
          releaseDate: "2021-12-05",
        },
      ],
    },
    {
      id: "beats-audio",
      name: "Beats Audio",
      logo: "/placeholder.svg?height=80&width=80",
      category: "audio",
      description:
        "Specialized in personal audio solutions including earbuds, headphones, and portable speakers for music lovers on the go.",
      rating: 4.6,
      reviewCount: 215,
      location: "Mombasa, Kenya",
      contact: {
        phone: "+254 767 890 123",
        email: "contact@beatsaudio.co.ke",
        website: "www.beatsaudio.co.ke",
      },
      openingHours: "Mon-Sun: 9:00 AM - 8:00 PM",
      amenities: ["Product Testing", "Personal Fitting", "Warranty Service", "Trade-In", "Gift Wrapping"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2016,
      brands: ["Apple", "Beats", "Samsung", "Jabra", "Anker", "Sony"],
      products: [
        {
          id: "airpods-pro-2",
          name: "Apple AirPods Pro (2nd Generation)",
          description:
            "Premium wireless earbuds with active noise cancellation, spatial audio, and seamless integration with Apple devices.",
          price: { amount: 35000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Earbuds",
          tags: ["Apple", "Wireless", "Noise Cancelling", "Premium"],
          specifications: {
            type: "In-ear",
            driver: "Custom",
            frequency: "Not specified",
            battery: "Up to 6 hours (30 hours with case)",
            connectivity: "Bluetooth 5.3",
            features: "Active Noise Cancellation, Transparency mode, Spatial Audio, H2 chip",
            weight: "5.3g per earbud",
          },
          warranty: "1 year manufacturer warranty",
          stock: 25,
          colors: ["White"],
          releaseDate: "2022-09-23",
        },
        {
          id: "samsung-buds2-pro",
          name: "Samsung Galaxy Buds2 Pro",
          description:
            "Premium earbuds with intelligent active noise cancellation, Hi-Fi sound, and seamless connectivity with Samsung devices.",
          price: { amount: 25000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Earbuds",
          tags: ["Samsung", "Wireless", "Noise Cancelling", "Premium"],
          specifications: {
            type: "In-ear",
            driver: "Custom coaxial 2-way",
            frequency: "Not specified",
            battery: "Up to 5 hours (18 hours with case)",
            connectivity: "Bluetooth 5.3",
            features: "Intelligent ANC, 24-bit Hi-Fi, 360 Audio, IPX7 water resistance",
            weight: "5.5g per earbud",
          },
          warranty: "1 year manufacturer warranty",
          stock: 18,
          colors: ["Graphite", "White", "Bora Purple"],
          releaseDate: "2022-08-26",
        },
        {
          id: "beats-fit-pro",
          name: "Beats Fit Pro True Wireless Earbuds",
          description:
            "Secure-fit earbuds with powerful sound, active noise cancellation, and flexible wingtips for active lifestyles.",
          price: { amount: 28000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Earbuds",
          tags: ["Beats", "Wireless", "Noise Cancelling", "Sports"],
          specifications: {
            type: "In-ear with wingtips",
            driver: "Custom",
            frequency: "Not specified",
            battery: "Up to 6 hours (24 hours with case)",
            connectivity: "Bluetooth 5.0",
            features: "Active Noise Cancellation, Transparency mode, Spatial Audio, H1 chip",
            weight: "5.6g per earbud",
          },
          warranty: "1 year manufacturer warranty",
          stock: 20,
          colors: ["Black", "White", "Sage Gray", "Stone Purple"],
          releaseDate: "2021-11-05",
        },
        {
          id: "anker-soundcore-3",
          name: "Anker Soundcore 3 Bluetooth Speaker",
          description:
            "Affordable portable speaker with impressive sound quality, long battery life, and durable design.",
          price: { amount: 8000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 25,
          category: "Portable Speakers",
          tags: ["Anker", "Wireless", "Portable", "Budget"],
          specifications: {
            drivers: "Dual full-range drivers and passive radiator",
            frequency: "Not specified",
            battery: "Up to 24 hours",
            connectivity: "Bluetooth 5.0",
            features: "BassUp technology, IPX7 waterproof, PartyCast for multiple speakers",
            dimensions: "170 x 70 x 50 mm",
            weight: "0.38kg",
          },
          warranty: "18 month manufacturer warranty",
          stock: 40,
          colors: ["Black", "Blue"],
          releaseDate: "2021-05-17",
        },
      ],
    },
  
    // Appliances Vendors
    {
      id: "home-tech",
      name: "Home Tech Solutions",
      logo: "/placeholder.svg?height=80&width=80",
      category: "appliances",
      description:
        "One-stop shop for home appliances ranging from kitchen equipment to smart home devices with professional installation.",
      rating: 4.7,
      reviewCount: 345,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 778 901 234",
        email: "sales@hometech.co.ke",
        website: "www.hometech.co.ke",
      },
      openingHours: "Mon-Sat: 8:00 AM - 7:00 PM, Sun: 10:00 AM - 5:00 PM",
      amenities: ["Installation Services", "Home Delivery", "Extended Warranty", "Trade-In", "Financing Options"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2011,
      brands: ["Samsung", "LG", "Bosch", "Miele", "Whirlpool", "Electrolux"],
      products: [
        {
          id: "samsung-fridge",
          name: "Samsung Family Hub Refrigerator",
          description:
            "Smart refrigerator with touchscreen display, internal cameras, and connected features for the modern kitchen.",
          price: { amount: 280000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Refrigerators",
          tags: ["Samsung", "Smart Appliance", "Premium", "Kitchen"],
          specifications: {
            type: "French Door",
            capacity: "635L",
            features: "Family Hub touchscreen, built-in cameras, Wi-Fi connectivity",
            energyRating: "A++",
            dimensions: "908 x 1825 x 733 mm",
            weight: "146kg",
            color: "Stainless Steel",
          },
          warranty: "2 year manufacturer warranty",
          stock: 8,
          colors: ["Stainless Steel", "Black Stainless Steel"],
          releaseDate: "2023-01-15",
        },
        {
          id: "lg-washing-machine",
          name: "LG AI Direct Drive Washing Machine",
          description:
            "Smart washing machine with AI technology that detects fabric types and optimizes wash cycles for better care.",
          price: { amount: 120000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Washing Machines",
          tags: ["LG", "Smart Appliance", "Premium", "Laundry"],
          specifications: {
            type: "Front Load",
            capacity: "10.5kg",
            features: "AI Direct Drive, TurboWash, Steam+, Wi-Fi connectivity",
            energyRating: "A+++",
            spinSpeed: "1400 RPM",
            dimensions: "600 x 850 x 565 mm",
            weight: "70kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 12,
          colors: ["White", "Silver"],
          releaseDate: "2022-11-10",
        },
        {
          id: "bosch-dishwasher",
          name: "Bosch Series 6 Dishwasher",
          description:
            "Premium dishwasher with quiet operation, flexible loading options, and excellent cleaning performance.",
          price: { amount: 95000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Dishwashers",
          tags: ["Bosch", "Premium", "Kitchen"],
          specifications: {
            type: "Built-in",
            capacity: "14 place settings",
            features: "PerfectDry, Silence Program, Home Connect",
            energyRating: "A+++",
            noiseLevel: "42 dB",
            dimensions: "598 x 815 x 573 mm",
            weight: "35kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 10,
          colors: ["Stainless Steel", "White"],
          releaseDate: "2023-02-20",
        },
        {
          id: "miele-oven",
          name: "Miele Dialog Oven",
          description:
            "Revolutionary oven with electromagnetic waves technology for precise and faster cooking with exceptional results.",
          price: { amount: 350000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 10,
          category: "Ovens",
          tags: ["Miele", "Premium", "Kitchen", "Smart Appliance"],
          specifications: {
            type: "Built-in",
            capacity: "50L",
            features: "M Chef Technology, TasteControl, FoodView camera",
            energyRating: "A+",
            dimensions: "595 x 596 x 569 mm",
            weight: "45kg",
          },
          warranty: "2 year manufacturer warranty",
          stock: 5,
          colors: ["Stainless Steel", "Obsidian Black"],
          releaseDate: "2022-09-05",
        },
      ],
    },
    {
      id: "smart-living",
      name: "Smart Living",
      logo: "/placeholder.svg?height=80&width=80",
      category: "appliances",
      description:
        "Specialized in smart home technology, automation systems, and connected appliances for the modern home.",
      rating: 4.8,
      reviewCount: 198,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 789 012 345",
        email: "info@smartliving.co.ke",
        website: "www.smartliving.co.ke",
      },
      openingHours: "Mon-Fri: 9:00 AM - 6:00 PM, Sat: 10:00 AM - 4:00 PM, Closed on Sundays",
      amenities: [
        "Smart Home Consultation",
        "Professional Installation",
        "System Integration",
        "Remote Support",
        "Training",
      ],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2017,
      brands: ["Google", "Amazon", "Apple", "Philips Hue", "Ring", "Nest"],
      products: [
        {
          id: "google-nest-hub",
          name: "Google Nest Hub (2nd Gen)",
          description:
            "Smart display with Google Assistant, sleep tracking, and smart home control center for your connected devices.",
          price: { amount: 18000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Smart Displays",
          tags: ["Google", "Smart Home", "Assistant"],
          specifications: {
            display: "7-inch touchscreen",
            features: "Sleep Sensing, Google Assistant, smart home control, digital photo frame",
            connectivity: "Wi-Fi, Bluetooth, Thread",
            audio: "Full-range speaker with 50% more bass",
            dimensions: "178.5 x 118 x 67.3 mm",
            weight: "0.558kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 25,
          colors: ["Chalk", "Charcoal", "Mist", "Sand"],
          releaseDate: "2021-03-30",
        },
        {
          id: "amazon-echo-show",
          name: "Amazon Echo Show 10 (3rd Gen)",
          description:
            "Smart display with motion tracking that follows you around the room, Alexa assistant, and premium sound quality.",
          price: { amount: 30000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Smart Displays",
          tags: ["Amazon", "Smart Home", "Alexa"],
          specifications: {
            display: "10.1-inch HD touchscreen",
            features: "Motion tracking, Alexa, smart home hub, video calling, security camera",
            connectivity: "Wi-Fi, Bluetooth, Zigbee",
            audio: "2 x 1-inch tweeters and 3-inch woofer",
            dimensions: "251 x 230 x 172 mm",
            weight: "2.56kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 15,
          colors: ["Charcoal", "Glacier White"],
          releaseDate: "2021-02-25",
        },
        {
          id: "philips-hue-starter",
          name: "Philips Hue White and Color Ambiance Starter Kit",
          description:
            "Smart lighting system with bridge and color-changing bulbs that can be controlled via app or voice assistants.",
          price: { amount: 25000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Smart Lighting",
          tags: ["Philips", "Smart Home", "Lighting"],
          specifications: {
            contents: "Bridge and 3 color bulbs",
            bulbType: "E27 (screw base)",
            brightness: "806 lumens",
            features: "16 million colors, scenes, routines, voice control",
            connectivity: "Zigbee, Wi-Fi (bridge)",
            compatibility: "Amazon Alexa, Google Assistant, Apple HomeKit",
          },
          warranty: "2 year manufacturer warranty",
          stock: 20,
          colors: ["White"],
          releaseDate: "2023-01-10",
        },
        {
          id: "ring-doorbell-pro",
          name: "Ring Video Doorbell Pro 2",
          description:
            "Advanced video doorbell with head-to-toe HD video, 3D motion detection, and enhanced security features.",
          price: { amount: 28000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 15,
          category: "Smart Security",
          tags: ["Ring", "Smart Home", "Security"],
          specifications: {
            video: "1536p HD with HDR",
            audio: "Two-way talk with noise cancellation",
            features: "3D motion detection, Bird's Eye View, Alexa Greetings",
            connectivity: "Wi-Fi",
            powerSource: "Hardwired",
            dimensions: "114.3 x 49.5 x 22.4 mm",
          },
          warranty: "1 year manufacturer warranty",
          stock: 18,
          colors: ["Satin Nickel"],
          releaseDate: "2021-03-31",
        },
      ],
    },
  
    // Gaming Vendors
    {
      id: "game-zone",
      name: "Game Zone",
      logo: "/placeholder.svg?height=80&width=80",
      category: "gaming",
      description:
        "Ultimate gaming destination with the latest consoles, games, accessories, and gaming PCs for enthusiasts and casual gamers.",
      rating: 4.9,
      reviewCount: 412,
      location: "Nairobi, Kenya",
      contact: {
        phone: "+254 790 123 456",
        email: "info@gamezone.co.ke",
        website: "www.gamezone.co.ke",
      },
      openingHours: "Mon-Sun: 10:00 AM - 9:00 PM",
      amenities: ["Gaming Lounge", "Tournament Space", "Repair Services", "Trade-In", "Pre-orders"],
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      established: 2014,
      brands: ["Sony", "Microsoft", "Nintendo", "Razer", "Logitech", "SteelSeries"],
      products: [
        {
          id: "ps5-console",
          name: "PlayStation 5 Console - Disc Edition",
          description:
            "Next-generation gaming console with ultra-high-speed SSD, 3D audio, and haptic feedback for immersive gaming.",
          price: { amount: 85000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isPopular: true,
          category: "Gaming Consoles",
          tags: ["Sony", "PlayStation", "Console"],
          specifications: {
            cpu: "AMD Zen 2, 8 cores at 3.5GHz",
            gpu: "AMD RDNA 2, 10.28 TFLOPS",
            ram: "16GB GDDR6",
            storage: "825GB SSD",
            resolution: "Up to 8K",
            frameRate: "Up to 120fps",
            dimensions: "390 x 104 x 260 mm",
            weight: "4.5kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 10,
          colors: ["White"],
          releaseDate: "2020-11-12",
        },
        {
          id: "xbox-series-x",
          name: "Xbox Series X Console",
          description:
            "Microsoft's most powerful console ever with 4K gaming at up to 120fps, quick resume, and backward compatibility.",
          price: { amount: 80000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          category: "Gaming Consoles",
          tags: ["Microsoft", "Xbox", "Console"],
          specifications: {
            cpu: "AMD Zen 2, 8 cores at 3.8GHz",
            gpu: "AMD RDNA 2, 12 TFLOPS",
            ram: "16GB GDDR6",
            storage: "1TB SSD",
            resolution: "Up to 8K",
            frameRate: "Up to 120fps",
            dimensions: "151 x 151 x 301 mm",
            weight: "4.45kg",
          },
          warranty: "1 year manufacturer warranty",
          stock: 8,
          colors: ["Black"],
          releaseDate: "2020-11-10",
        },
        {
          id: "nintendo-switch-oled",
          name: "Nintendo Switch OLED Model",
          description:
            "Enhanced version of the popular Nintendo Switch with a vibrant 7-inch OLED screen and improved audio.",
          price: { amount: 45000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isNew: true,
          category: "Gaming Consoles",
          tags: ["Nintendo", "Switch", "Portable"],
          specifications: {
            display: "7-inch OLED touchscreen",
            cpu: "NVIDIA Custom Tegra",
            storage: "64GB (expandable)",
            battery: "4.5-9 hours",
            connectivity: "Wi-Fi, Bluetooth, Wired LAN (dock)",
            dimensions: "242 x 102 x 13.9 mm (with Joy-Con)",
            weight: "0.42kg (with Joy-Con)",
          },
          warranty: "1 year manufacturer warranty",
          stock: 15,
          colors: ["White", "Neon Red/Blue"],
          releaseDate: "2021-10-08",
        },
        {
          id: "razer-blackshark-v2",
          name: "Razer BlackShark V2 Pro Gaming Headset",
          description:
            "Wireless esports headset with THX Spatial Audio, detachable mic, and all-day comfort for competitive gaming.",
          price: { amount: 22000, currency: "KSH" },
          image: "/placeholder.svg?height=300&width=300",
          isDiscount: true,
          discountPercentage: 20,
          category: "Gaming Accessories",
          tags: ["Razer", "Headset", "Wireless", "Esports"],
          specifications: {
            type: "Over-ear",
            driver: "TriForce Titanium 50mm",
            frequency: "12Hz-28,000Hz",
            battery: "Up to 24 hours",
            connectivity: "2.4GHz wireless, 3.5mm",
            features: "THX Spatial Audio, detachable HyperClear mic, memory foam ear cushions",
            weight: "320g",
          },
          warranty: "2 year manufacturer warranty",
          stock: 20,
          colors: ["Black"],
          releaseDate: "2020-07-30",
        },
      ],
    },
  ]
  
  