import type { ProductRanking } from "@/components/TrendingPopularSection"

// Mock data for trending products in entertainment
export const trendingProducts: ProductRanking[] = [
  {
    id: "tr1",
    name: "Kenyan Music Festival Tickets",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 35.99,
      currency: "KSh",
    },
    rating: 4.9,
    category: "Events",
    vendor: "Nairobi Events",
    rank: 1,
    url: "/entertainment/shop/products/music-festival",
    badges: ["trending", "hot"],
  },
  {
    id: "tr2",
    name: "Safari Park Adventure Pass",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 45.5,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Attractions",
    vendor: "Kenya Wildlife Tours",
    rank: 2,
    url: "/entertainment/shop/products/safari-park-pass",
    badges: ["trending"],
  },
  {
    id: "tr3",
    name: "Premium Movie Theater Subscription",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 29.99,
      currency: "KSh",
    },
    rating: 4.7,
    category: "Movies",
    vendor: "Nairobi Cinema",
    rank: 3,
    url: "/entertainment/shop/products/movie-subscription",
    badges: ["trending", "popular"],
  },
  {
    id: "tr4",
    name: "Local Comedy Show Tickets",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 18.75,
      currency: "KSh",
    },
    rating: 4.6,
    category: "Events",
    vendor: "Laugh Factory Kenya",
    rank: 4,
    url: "/entertainment/shop/products/comedy-show",
    badges: ["trending"],
  },
  {
    id: "tr5",
    name: "Virtual Reality Gaming Session",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 25.99,
      currency: "KSh",
    },
    rating: 4.5,
    category: "Gaming",
    vendor: "Digital Playground",
    rank: 5,
    url: "/entertainment/shop/products/vr-gaming",
    badges: ["trending", "new"],
  },
]

// Mock data for most popular products in entertainment
export const popularProducts: ProductRanking[] = [
  {
    id: "pop1",
    name: "Maasai Mara Safari Experience",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 149.99,
      currency: "KSh",
    },
    rating: 4.9,
    category: "Attractions",
    vendor: "Kenya Wildlife Tours",
    rank: 1,
    url: "/entertainment/shop/products/maasai-mara-safari",
    badges: ["popular", "hot"],
  },
  {
    id: "pop2",
    name: "Kenyan Music Streaming Subscription",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 9.5,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Music",
    vendor: "Kenyan Beats",
    rank: 2,
    url: "/entertainment/shop/products/music-streaming",
    badges: ["popular"],
  },
  {
    id: "pop3",
    name: "Nairobi National Park Tour",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 55.99,
      currency: "KSh",
    },
    rating: 4.7,
    category: "Attractions",
    vendor: "Kenya Wildlife Tours",
    rank: 3,
    url: "/entertainment/shop/products/national-park-tour",
    badges: ["popular", "trending"],
  },
  {
    id: "pop4",
    name: "Family Theme Park Day Pass",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 65.25,
      currency: "KSh",
    },
    rating: 4.6,
    category: "Attractions",
    vendor: "Fun World Kenya",
    rank: 4,
    url: "/entertainment/shop/products/theme-park-pass",
    badges: ["popular"],
  },
  {
    id: "pop5",
    name: "Live Music Concert Tickets",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 42.75,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Events",
    vendor: "Nairobi Events",
    rank: 5,
    url: "/entertainment/shop/products/concert-tickets",
    badges: ["popular", "hot"],
  },
]

