import { Sparkles, Droplet, Palette, Scissors, SprayCanIcon as Spray, Leaf } from "lucide-react"
import type React from "react"

// Types
interface Price {
  amount: number
  currency: string
}

interface BeautyProduct {
  id: string
  name: string
  imageUrl: string
  images?: string[]
  currentPrice: Price
  originalPrice: Price
  category: string
  subcategory: string
  brand: string
  description: string
  rating?: number
  reviewCount?: number
  stockStatus: "In Stock" | "Low Stock" | "Out of Stock"
  stockCount?: number
  discount?: number
  isNew?: boolean
  isBestSeller?: boolean
  isOrganic?: boolean
  ingredients?: string[]
  suitableFor?: string[]
  howToUse?: string
  benefits?: string[]
  vendorId: string
  tags?: string[]
  dateAdded?: string
  skinType?: string[]
  concerns?: string[]
  freeGift?: boolean
}

interface Vendor {
  id: string
  name: string
  logo: string
  location: string
  rating?: number
  reviewCount?: number
  verified?: boolean
  website?: string
  description?: string
}

interface Category {
  id: string
  name: string
  icon: React.ReactNode
  subcategories: Subcategory[]
}

interface Subcategory {
  id: string
  name: string
  productCount: number
}

// Categories
export const beautyCategories: Category[] = [
  {
    id: "skincare",
    name: "Skincare",
    icon: <Sparkles className="h-4 w-4 mr-2" />,
    subcategories: [
      { id: "cleansers", name: "Cleansers", productCount: 24 },
      { id: "moisturizers", name: "Moisturizers", productCount: 32 },
      { id: "serums", name: "Serums & Treatments", productCount: 28 },
      { id: "masks", name: "Masks", productCount: 18 },
      { id: "sunscreen", name: "Sunscreen", productCount: 15 },
      { id: "eye-care", name: "Eye Care", productCount: 12 },
    ],
  },
  {
    id: "makeup",
    name: "Makeup",
    
    subcategories: [
      { id: "face", name: "Face", productCount: 36 },
      { id: "eyes", name: "Eyes", productCount: 42 },
      { id: "lips", name: "Lips", productCount: 38 },
      { id: "cheeks", name: "Cheeks", productCount: 24 },
      { id: "brushes", name: "Brushes & Tools", productCount: 18 },
    ],
  },
  {
    id: "haircare",
    name: "Hair Care",
    
    subcategories: [
      { id: "shampoo", name: "Shampoo", productCount: 22 },
      { id: "conditioner", name: "Conditioner", productCount: 20 },
      { id: "treatments", name: "Treatments", productCount: 16 },
      { id: "styling", name: "Styling", productCount: 28 },
      { id: "hair-color", name: "Hair Color", productCount: 14 },
    ],
  },
  {
    id: "fragrance",
    name: "Fragrance",
    
    subcategories: [
      { id: "women-perfume", name: "Women's Perfume", productCount: 32 },
      { id: "men-cologne", name: "Men's Cologne", productCount: 28 },
      { id: "unisex", name: "Unisex", productCount: 18 },
      { id: "gift-sets", name: "Gift Sets", productCount: 15 },
    ],
  },
  {
    id: "bodycare",
    name: "Body Care",
   
    subcategories: [
      { id: "body-wash", name: "Body Wash", productCount: 20 },
      { id: "lotions", name: "Lotions & Creams", productCount: 24 },
      { id: "scrubs", name: "Scrubs & Exfoliants", productCount: 16 },
      { id: "oils", name: "Body Oils", productCount: 12 },
      { id: "hand-care", name: "Hand Care", productCount: 10 },
    ],
  },
  {
    id: "natural",
    name: "Natural & Organic",
  
    subcategories: [
      { id: "organic-skincare", name: "Organic Skincare", productCount: 22 },
      { id: "organic-makeup", name: "Organic Makeup", productCount: 18 },
      { id: "organic-haircare", name: "Organic Haircare", productCount: 14 },
      { id: "organic-bodycare", name: "Organic Bodycare", productCount: 16 },
    ],
  },
]

// Vendors
export const beautyVendors: Vendor[] = [
  {
    id: "v1",
    name: "Glow & Radiance",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Nairobi, Kenya",
    rating: 4.8,
    reviewCount: 342,
    verified: true,
    website: "https://glowandradiance.co.ke",
    description: "Premium skincare and beauty products for all skin types.",
  },
  {
    id: "v2",
    name: "Natural Beauty Co.",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Mombasa, Kenya",
    rating: 4.7,
    reviewCount: 256,
    verified: true,
    website: "https://naturalbeautyco.co.ke",
    description: "Organic and natural beauty products made with locally sourced ingredients.",
  },
  {
    id: "v3",
    name: "Luxe Cosmetics",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Kisumu, Kenya",
    rating: 4.9,
    reviewCount: 189,
    verified: true,
    website: "https://luxecosmetics.co.ke",
    description: "Luxury makeup and skincare products from top international brands.",
  },
  {
    id: "v4",
    name: "Pure Essence",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Nakuru, Kenya",
    rating: 4.6,
    reviewCount: 127,
    verified: true,
    website: "https://puressence.co.ke",
    description: "Fragrance specialists offering a wide range of perfumes and colognes.",
  },
  {
    id: "v5",
    name: "Hair Haven",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Eldoret, Kenya",
    rating: 4.5,
    reviewCount: 98,
    verified: false,
    website: "https://hairhaven.co.ke",
    description: "Specialized in premium hair care products for all hair types.",
  },
  {
    id: "v6",
    name: "Organic Beauty",
    logo: "/placeholder.svg?height=60&width=60",
    location: "Thika, Kenya",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    website: "https://organicbeauty.co.ke",
    description: "100% organic and cruelty-free beauty products.",
  },
]

// Products
export const beautyProducts: BeautyProduct[] = [
  // Skincare - Cleansers
  {
    id: "sc1",
    name: "Gentle Foaming Cleanser with Hyaluronic Acid",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1800, currency: "KSH" },
    originalPrice: { amount: 2500, currency: "KSH" },
    category: "skincare",
    subcategory: "cleansers",
    brand: "Glow & Radiance",
    description:
      "A gentle foaming cleanser that removes impurities without stripping the skin's natural moisture. Enriched with hyaluronic acid for added hydration.",
    rating: 4.8,
    reviewCount: 124,
    stockStatus: "In Stock",
    stockCount: 45,
    discount: 28,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Hyaluronic Acid", "Glycerin", "Aloe Vera", "Chamomile Extract"],
    suitableFor: ["All Skin Types", "Sensitive Skin"],
    skinType: ["Dry", "Normal", "Combination", "Sensitive"],
    concerns: ["Dryness", "Dullness"],
    howToUse:
      "Apply to damp face, massage gently in circular motions, and rinse thoroughly with lukewarm water. Use morning and evening.",
    benefits: ["Removes impurities", "Hydrates skin", "Soothes sensitivity", "Maintains skin barrier"],
    vendorId: "v1",
    tags: ["Cleanser", "Hydrating", "Gentle"],
    dateAdded: "2025-01-15T10:30:00Z",
  },
  {
    id: "sc2",
    name: "Charcoal Deep Cleansing Gel",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1500, currency: "KSH" },
    originalPrice: { amount: 2200, currency: "KSH" },
    category: "skincare",
    subcategory: "cleansers",
    brand: "Pure Essence",
    description:
      "Deep cleansing gel with activated charcoal that draws out impurities, unclogs pores, and removes excess oil for a clearer complexion.",
    rating: 4.7,
    reviewCount: 98,
    stockStatus: "In Stock",
    stockCount: 32,
    discount: 32,
    isNew: false,
    isBestSeller: false,
    isOrganic: false,
    ingredients: ["Activated Charcoal", "Salicylic Acid", "Tea Tree Oil", "Witch Hazel"],
    suitableFor: ["Oily Skin", "Acne-Prone Skin"],
    skinType: ["Oily", "Combination", "Acne-Prone"],
    concerns: ["Acne", "Oiliness", "Enlarged Pores"],
    howToUse: "Apply to damp face, massage gently focusing on T-zone, and rinse thoroughly. Use once daily.",
    benefits: ["Removes impurities", "Controls oil", "Unclogs pores", "Prevents breakouts"],
    vendorId: "v3",
    tags: ["Cleanser", "Charcoal", "Deep Cleansing"],
    dateAdded: "2025-02-10T10:30:00Z",
  },
  {
    id: "sc3",
    name: "Organic Rose Cleansing Balm",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 2800, currency: "KSH" },
    originalPrice: { amount: 3500, currency: "KSH" },
    category: "skincare",
    subcategory: "cleansers",
    brand: "Organic Beauty",
    description:
      "Luxurious cleansing balm that melts away makeup and impurities while nourishing the skin with organic rose oil and shea butter.",
    rating: 4.9,
    reviewCount: 156,
    stockStatus: "In Stock",
    stockCount: 18,
    discount: 20,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Organic Rose Oil", "Shea Butter", "Jojoba Oil", "Vitamin E"],
    suitableFor: ["All Skin Types", "Dry Skin", "Mature Skin"],
    skinType: ["Dry", "Normal", "Mature", "Sensitive"],
    concerns: ["Dryness", "Makeup Removal", "Dullness"],
    howToUse:
      "Massage onto dry skin, add water to emulsify, then rinse clean. Follow with your regular cleanser if desired.",
    benefits: ["Removes makeup", "Hydrates skin", "Soothes irritation", "Nourishes"],
    vendorId: "v6",
    tags: ["Cleanser", "Balm", "Organic", "Rose"],
    dateAdded: "2025-03-28T10:30:00Z",
    freeGift: true,
  },

  // Skincare - Moisturizers
  {
    id: "sm1",
    name: "Hydra-Boost Gel Cream with Ceramides",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 2500, currency: "KSH" },
    originalPrice: { amount: 3200, currency: "KSH" },
    category: "skincare",
    subcategory: "moisturizers",
    brand: "Glow & Radiance",
    description:
      "Lightweight gel-cream that provides 72-hour hydration with ceramides and hyaluronic acid. Absorbs quickly with no greasy residue.",
    rating: 4.8,
    reviewCount: 187,
    stockStatus: "In Stock",
    stockCount: 42,
    discount: 22,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Ceramides", "Hyaluronic Acid", "Glycerin", "Niacinamide"],
    suitableFor: ["All Skin Types", "Dehydrated Skin"],
    skinType: ["Normal", "Combination", "Oily", "Dehydrated"],
    concerns: ["Dehydration", "Dullness", "Fine Lines"],
    howToUse: "Apply to clean face and neck morning and evening. Can be used under makeup.",
    benefits: ["Intense hydration", "Strengthens skin barrier", "Oil-free formula", "Non-comedogenic"],
    vendorId: "v1",
    tags: ["Moisturizer", "Gel Cream", "Hydrating"],
    dateAdded: "2025-01-20T10:30:00Z",
  },
  {
    id: "sm2",
    name: "Rich Repair Night Cream with Peptides",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 3500, currency: "KSH" },
    originalPrice: { amount: 4800, currency: "KSH" },
    category: "skincare",
    subcategory: "moisturizers",
    brand: "Luxe Cosmetics",
    description:
      "Rich, nourishing night cream with peptides and retinol that works overnight to repair and rejuvenate skin while you sleep.",
    rating: 4.9,
    reviewCount: 142,
    stockStatus: "In Stock",
    stockCount: 25,
    discount: 27,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Peptides", "Retinol", "Shea Butter", "Vitamin E"],
    suitableFor: ["Mature Skin", "Dry Skin", "Normal Skin"],
    skinType: ["Dry", "Normal", "Mature"],
    concerns: ["Aging", "Fine Lines", "Wrinkles", "Dryness"],
    howToUse: "Apply to clean face and neck in the evening. Avoid eye area.",
    benefits: ["Reduces fine lines", "Improves elasticity", "Deeply moisturizes", "Enhances skin renewal"],
    vendorId: "v3",
    tags: ["Moisturizer", "Night Cream", "Anti-aging"],
    dateAdded: "2025-02-05T10:30:00Z",
  },
  {
    id: "sm3",
    name: "Organic Aloe & Cucumber Day Moisturizer SPF 30",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 2200, currency: "KSH" },
    originalPrice: { amount: 2800, currency: "KSH" },
    category: "skincare",
    subcategory: "moisturizers",
    brand: "Organic Beauty",
    description:
      "Lightweight day moisturizer with organic aloe vera and cucumber extract that hydrates while providing SPF 30 protection.",
    rating: 4.7,
    reviewCount: 112,
    stockStatus: "In Stock",
    stockCount: 38,
    discount: 21,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Organic Aloe Vera", "Cucumber Extract", "Zinc Oxide", "Vitamin E"],
    suitableFor: ["All Skin Types", "Sensitive Skin"],
    skinType: ["Normal", "Combination", "Sensitive", "Oily"],
    concerns: ["Sun Protection", "Hydration", "Redness"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours when outdoors.",
    benefits: ["Hydrates skin", "Protects from UV rays", "Soothes irritation", "Non-greasy formula"],
    vendorId: "v6",
    tags: ["Moisturizer", "SPF", "Organic", "Day Cream"],
    dateAdded: "2025-03-25T10:30:00Z",
  },

  // Skincare - Serums
  {
    id: "ss1",
    name: "Vitamin C Brightening Serum 20%",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 3200, currency: "KSH" },
    originalPrice: { amount: 4500, currency: "KSH" },
    category: "skincare",
    subcategory: "serums",
    brand: "Glow & Radiance",
    description:
      "Potent 20% vitamin C serum that brightens skin, reduces dark spots, and boosts collagen production for a radiant complexion.",
    rating: 4.9,
    reviewCount: 215,
    stockStatus: "In Stock",
    stockCount: 30,
    discount: 29,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["20% L-Ascorbic Acid", "Ferulic Acid", "Vitamin E", "Hyaluronic Acid"],
    suitableFor: ["All Skin Types", "Dull Skin", "Hyperpigmentation"],
    skinType: ["Normal", "Combination", "Dry", "Oily"],
    concerns: ["Dark Spots", "Dullness", "Uneven Tone", "Fine Lines"],
    howToUse: "Apply 3-4 drops to clean face and neck in the morning before moisturizer and sunscreen.",
    benefits: ["Brightens skin", "Reduces dark spots", "Boosts collagen", "Antioxidant protection"],
    vendorId: "v1",
    tags: ["Serum", "Vitamin C", "Brightening"],
    dateAdded: "2025-01-10T10:30:00Z",
  },
  {
    id: "ss2",
    name: "Hyaluronic Acid Hydrating Serum",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 2800, currency: "KSH" },
    originalPrice: { amount: 3500, currency: "KSH" },
    category: "skincare",
    subcategory: "serums",
    brand: "Pure Essence",
    description:
      "Intensely hydrating serum with multi-molecular hyaluronic acid that plumps skin and reduces the appearance of fine lines.",
    rating: 4.8,
    reviewCount: 178,
    stockStatus: "In Stock",
    stockCount: 42,
    discount: 20,
    isNew: false,
    isBestSeller: false,
    isOrganic: false,
    ingredients: ["Multi-molecular Hyaluronic Acid", "B5", "Glycerin", "Aloe Vera"],
    suitableFor: ["All Skin Types", "Dehydrated Skin"],
    skinType: ["Dry", "Normal", "Combination", "Dehydrated"],
    concerns: ["Dehydration", "Fine Lines", "Dullness"],
    howToUse: "Apply to damp skin after cleansing. Follow with moisturizer to lock in hydration.",
    benefits: ["Intense hydration", "Plumps skin", "Reduces fine lines", "Improves skin texture"],
    vendorId: "v4",
    tags: ["Serum", "Hyaluronic Acid", "Hydrating"],
    dateAdded: "2025-02-15T10:30:00Z",
  },
  {
    id: "ss3",
    name: "Organic Bakuchiol Retinol Alternative Serum",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 3800, currency: "KSH" },
    originalPrice: { amount: 4800, currency: "KSH" },
    category: "skincare",
    subcategory: "serums",
    brand: "Organic Beauty",
    description:
      "Plant-based retinol alternative serum with bakuchiol that reduces fine lines and improves skin texture without irritation.",
    rating: 4.7,
    reviewCount: 98,
    stockStatus: "Low Stock",
    stockCount: 8,
    discount: 21,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Bakuchiol", "Squalane", "Rosehip Oil", "Vitamin E"],
    suitableFor: ["All Skin Types", "Sensitive Skin", "Pregnant Women"],
    skinType: ["Sensitive", "Normal", "Dry", "Mature"],
    concerns: ["Aging", "Fine Lines", "Texture", "Sensitivity"],
    howToUse: "Apply 2-3 drops to clean face and neck in the evening. Can be used during pregnancy.",
    benefits: ["Reduces fine lines", "Improves texture", "Non-irritating", "Safe for pregnancy"],
    vendorId: "v6",
    tags: ["Serum", "Bakuchiol", "Anti-aging", "Organic"],
    dateAdded: "2025-03-20T10:30:00Z",
    freeGift: true,
  },

  // Makeup - Face
  {
    id: "mf1",
    name: "Skin Perfecting Foundation SPF 25",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 2800, currency: "KSH" },
    originalPrice: { amount: 3500, currency: "KSH" },
    category: "makeup",
    subcategory: "face",
    brand: "Luxe Cosmetics",
    description:
      "Medium to full coverage foundation with a natural finish that lasts all day. Contains SPF 25 and skincare ingredients.",
    rating: 4.8,
    reviewCount: 215,
    stockStatus: "In Stock",
    stockCount: 45,
    discount: 20,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Hyaluronic Acid", "Vitamin E", "Titanium Dioxide", "Iron Oxides"],
    suitableFor: ["All Skin Types"],
    skinType: ["Normal", "Combination", "Dry", "Oily"],
    concerns: ["Uneven Tone", "Redness", "Blemishes"],
    howToUse: "Apply with fingers, brush, or sponge. Build coverage as needed.",
    benefits: ["Medium to full coverage", "Natural finish", "SPF protection", "Long-wearing"],
    vendorId: "v3",
    tags: ["Foundation", "SPF", "Medium Coverage"],
    dateAdded: "2025-01-15T10:30:00Z",
  },
  {
    id: "mf2",
    name: "Radiance Boosting Primer",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1800, currency: "KSH" },
    originalPrice: { amount: 2500, currency: "KSH" },
    category: "makeup",
    subcategory: "face",
    brand: "Glow & Radiance",
    description: "Illuminating primer that creates a smooth canvas for makeup while adding a subtle glow to the skin.",
    rating: 4.7,
    reviewCount: 156,
    stockStatus: "In Stock",
    stockCount: 32,
    discount: 28,
    isNew: false,
    isBestSeller: false,
    isOrganic: false,
    ingredients: ["Mica", "Silicones", "Vitamin E", "Jojoba Oil"],
    suitableFor: ["All Skin Types"],
    skinType: ["Normal", "Dry", "Dull"],
    concerns: ["Dullness", "Uneven Texture", "Makeup Longevity"],
    howToUse: "Apply a small amount to clean, moisturized skin before foundation.",
    benefits: ["Extends makeup wear", "Adds subtle glow", "Smooths skin texture", "Hydrates"],
    vendorId: "v1",
    tags: ["Primer", "Illuminating", "Radiance"],
    dateAdded: "2025-02-10T10:30:00Z",
  },

  // Makeup - Eyes
  {
    id: "me1",
    name: "24-Hour Waterproof Liquid Eyeliner",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1200, currency: "KSH" },
    originalPrice: { amount: 1800, currency: "KSH" },
    category: "makeup",
    subcategory: "eyes",
    brand: "Luxe Cosmetics",
    description:
      "Ultra-precise liquid eyeliner with a fine-tip applicator that creates sharp lines and stays put for 24 hours.",
    rating: 4.9,
    reviewCount: 245,
    stockStatus: "In Stock",
    stockCount: 50,
    discount: 33,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Carbon Black", "Film Formers", "Glycerin"],
    suitableFor: ["All Eye Types"],
    concerns: ["Smudging", "Precision", "Longevity"],
    howToUse: "Start from the inner corner and draw along the lash line. For wings, extend outward and upward.",
    benefits: ["24-hour wear", "Waterproof", "Smudge-proof", "Ultra-precise tip"],
    vendorId: "v3",
    tags: ["Eyeliner", "Waterproof", "Long-lasting"],
    dateAdded: "2025-01-20T10:30:00Z",
  },
  {
    id: "me2",
    name: "Volumizing Mascara with Keratin",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1500, currency: "KSH" },
    originalPrice: { amount: 2200, currency: "KSH" },
    category: "makeup",
    subcategory: "eyes",
    brand: "Glow & Radiance",
    description:
      "Volumizing mascara with keratin that builds dramatic lashes without clumping. Conditions and strengthens lashes over time.",
    rating: 4.7,
    reviewCount: 178,
    stockStatus: "In Stock",
    stockCount: 38,
    discount: 32,
    isNew: true,
    isBestSeller: false,
    isOrganic: false,
    ingredients: ["Keratin", "Vitamin E", "Panthenol", "Jojoba Oil"],
    suitableFor: ["All Lash Types"],
    concerns: ["Volume", "Length", "Lash Health"],
    howToUse: "Apply from root to tip with zigzag motion. Build layers for more volume.",
    benefits: ["Volumizes", "Lengthens", "Conditions", "No clumping"],
    vendorId: "v1",
    tags: ["Mascara", "Volumizing", "Keratin"],
    dateAdded: "2025-03-15T10:30:00Z",
  },

  // Makeup - Lips
  {
    id: "ml1",
    name: "Long-Wear Matte Liquid Lipstick",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1600, currency: "KSH" },
    originalPrice: { amount: 2200, currency: "KSH" },
    category: "makeup",
    subcategory: "lips",
    brand: "Luxe Cosmetics",
    description:
      "Long-wearing liquid lipstick with a comfortable matte finish that stays put for up to 12 hours without drying lips.",
    rating: 4.8,
    reviewCount: 198,
    stockStatus: "In Stock",
    stockCount: 42,
    discount: 27,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Silicones", "Vitamin E", "Shea Butter", "Jojoba Oil"],
    suitableFor: ["All Skin Types"],
    concerns: ["Longevity", "Comfort", "Color Payoff"],
    howToUse: "Apply to clean, dry lips. Allow to dry completely before eating or drinking.",
    benefits: ["12-hour wear", "Transfer-proof", "Comfortable matte finish", "Intense color"],
    vendorId: "v3",
    tags: ["Lipstick", "Matte", "Long-lasting"],
    dateAdded: "2025-01-25T10:30:00Z",
  },
  {
    id: "ml2",
    name: "Organic Tinted Lip Balm SPF 15",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 950, currency: "KSH" },
    originalPrice: { amount: 1200, currency: "KSH" },
    category: "makeup",
    subcategory: "lips",
    brand: "Organic Beauty",
    description:
      "Hydrating tinted lip balm with organic ingredients that provides a sheer wash of color while protecting lips with SPF 15.",
    rating: 4.6,
    reviewCount: 145,
    stockStatus: "In Stock",
    stockCount: 55,
    discount: 21,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Organic Shea Butter", "Coconut Oil", "Beeswax", "Zinc Oxide"],
    suitableFor: ["All Skin Types", "Dry Lips"],
    concerns: ["Dry Lips", "Sun Protection", "Natural Look"],
    howToUse: "Apply directly to lips as needed throughout the day.",
    benefits: ["Hydrates", "Adds sheer color", "SPF protection", "Natural ingredients"],
    vendorId: "v6",
    tags: ["Lip Balm", "Tinted", "SPF", "Organic"],
    dateAdded: "2025-03-10T10:30:00Z",
  },

  // Haircare - Shampoo
  {
    id: "hs1",
    name: "Moisturizing Shampoo for Dry Hair",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1800, currency: "KSH" },
    originalPrice: { amount: 2500, currency: "KSH" },
    category: "haircare",
    subcategory: "shampoo",
    brand: "Hair Haven",
    description:
      "Deeply moisturizing shampoo that cleanses while replenishing dry, damaged hair with argan oil and keratin.",
    rating: 4.7,
    reviewCount: 165,
    stockStatus: "In Stock",
    stockCount: 40,
    discount: 28,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Argan Oil", "Keratin", "Glycerin", "Panthenol"],
    suitableFor: ["Dry Hair", "Damaged Hair", "Color-Treated Hair"],
    concerns: ["Dryness", "Damage", "Frizz"],
    howToUse: "Apply to wet hair, massage into scalp and hair, then rinse thoroughly.",
    benefits: ["Hydrates dry hair", "Repairs damage", "Reduces frizz", "Adds shine"],
    vendorId: "v5",
    tags: ["Shampoo", "Moisturizing", "Dry Hair"],
    dateAdded: "2025-02-05T10:30:00Z",
  },
  {
    id: "hs2",
    name: "Organic Clarifying Tea Tree Shampoo",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1600, currency: "KSH" },
    originalPrice: { amount: 2200, currency: "KSH" },
    category: "haircare",
    subcategory: "shampoo",
    brand: "Organic Beauty",
    description:
      "Clarifying shampoo with organic tea tree oil that removes buildup while balancing the scalp for healthier hair.",
    rating: 4.6,
    reviewCount: 132,
    stockStatus: "In Stock",
    stockCount: 35,
    discount: 27,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Organic Tea Tree Oil", "Aloe Vera", "Peppermint Oil", "Witch Hazel"],
    suitableFor: ["Oily Hair", "Oily Scalp", "All Hair Types"],
    concerns: ["Oiliness", "Buildup", "Scalp Health"],
    howToUse: "Apply to wet hair, massage into scalp, leave for 1-2 minutes, then rinse thoroughly.",
    benefits: ["Removes buildup", "Balances scalp", "Refreshes", "Adds shine"],
    vendorId: "v6",
    tags: ["Shampoo", "Clarifying", "Tea Tree", "Organic"],
    dateAdded: "2025-03-18T10:30:00Z",
  },

  // Fragrance - Women's Perfume
  {
    id: "fp1",
    name: "Floral Elegance Eau de Parfum",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 4500, currency: "KSH" },
    originalPrice: { amount: 6000, currency: "KSH" },
    category: "fragrance",
    subcategory: "women-perfume",
    brand: "Pure Essence",
    description:
      "Elegant floral fragrance with notes of rose, jasmine, and vanilla for a sophisticated and feminine scent.",
    rating: 4.9,
    reviewCount: 178,
    stockStatus: "In Stock",
    stockCount: 25,
    discount: 25,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Alcohol", "Fragrance", "Water"],
    suitableFor: ["Women"],
    howToUse: "Spray on pulse points: wrists, neck, and behind ears.",
    benefits: ["Long-lasting", "Elegant scent", "Sophisticated", "Day to evening wear"],
    vendorId: "v4",
    tags: ["Perfume", "Floral", "Elegant"],
    dateAdded: "2025-01-15T10:30:00Z",
  },
  {
    id: "fp2",
    name: "Citrus Breeze Eau de Toilette",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 3200, currency: "KSH" },
    originalPrice: { amount: 4000, currency: "KSH" },
    category: "fragrance",
    subcategory: "women-perfume",
    brand: "Pure Essence",
    description:
      "Fresh and invigorating citrus fragrance with notes of bergamot, lemon, and green tea perfect for daily wear.",
    rating: 4.7,
    reviewCount: 145,
    stockStatus: "In Stock",
    stockCount: 30,
    discount: 20,
    isNew: true,
    isBestSeller: false,
    isOrganic: false,
    ingredients: ["Alcohol", "Fragrance", "Water"],
    suitableFor: ["Women"],
    howToUse: "Spray on pulse points: wrists, neck, and behind ears.",
    benefits: ["Fresh scent", "Uplifting", "Perfect for daytime", "Energizing"],
    vendorId: "v4",
    tags: ["Perfume", "Citrus", "Fresh"],
    dateAdded: "2025-03-20T10:30:00Z",
    freeGift: true,
  },

  // Body Care - Body Wash
  {
    id: "bw1",
    name: "Lavender & Chamomile Relaxing Body Wash",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1200, currency: "KSH" },
    originalPrice: { amount: 1800, currency: "KSH" },
    category: "bodycare",
    subcategory: "body-wash",
    brand: "Pure Essence",
    description:
      "Calming body wash with lavender and chamomile that cleanses while promoting relaxation for a spa-like experience.",
    rating: 4.8,
    reviewCount: 156,
    stockStatus: "In Stock",
    stockCount: 45,
    discount: 33,
    isNew: false,
    isBestSeller: true,
    isOrganic: false,
    ingredients: ["Lavender Oil", "Chamomile Extract", "Glycerin", "Aloe Vera"],
    suitableFor: ["All Skin Types", "Sensitive Skin"],
    skinType: ["All", "Sensitive"],
    concerns: ["Stress Relief", "Gentle Cleansing"],
    howToUse: "Apply to wet skin, massage into a lather, then rinse thoroughly.",
    benefits: ["Cleanses", "Relaxes", "Soothes", "Hydrates"],
    vendorId: "v4",
    tags: ["Body Wash", "Relaxing", "Lavender"],
    dateAdded: "2025-02-10T10:30:00Z",
  },
  {
    id: "bw2",
    name: "Organic Coconut & Shea Nourishing Body Wash",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    currentPrice: { amount: 1500, currency: "KSH" },
    originalPrice: { amount: 2000, currency: "KSH" },
    category: "bodycare",
    subcategory: "body-wash",
    brand: "Organic Beauty",
    description:
      "Nourishing body wash with organic coconut oil and shea butter that cleanses while deeply moisturizing dry skin.",
    rating: 4.7,
    reviewCount: 132,
    stockStatus: "In Stock",
    stockCount: 38,
    discount: 25,
    isNew: true,
    isBestSeller: false,
    isOrganic: true,
    ingredients: ["Organic Coconut Oil", "Shea Butter", "Aloe Vera", "Vitamin E"],
    suitableFor: ["Dry Skin", "Normal Skin", "Sensitive Skin"],
    skinType: ["Dry", "Normal", "Sensitive"],
    concerns: ["Dryness", "Gentle Cleansing"],
    howToUse: "Apply to wet skin, massage into a lather, then rinse thoroughly.",
    benefits: ["Cleanses", "Moisturizes", "Nourishes", "Soothes"],
    vendorId: "v6",
    tags: ["Body Wash", "Moisturizing", "Organic", "Coconut"],
    dateAdded: "2025-03-15T10:30:00Z",
  },
]
