export type CarDealCategory =
  | "Luxury"
  | "SUV"
  | "Sedan"
  | "Electric"
  | "Hybrid"
  | "Sports"
  | "Vintage"
  | "Truck"
  | "Convertible"
  | "Minivan"

export type CarCondition = "New" | "Used" | "Certified Pre-Owned"

export type DrivetrainType = "FWD" | "RWD" | "AWD" | "4WD"

export type TransmissionType = "Automatic" | "Manual" | "CVT" | "Dual-Clutch"

export type FuelType = "Gasoline" | "Diesel" | "Electric" | "Hybrid" | "Plug-in Hybrid" | "Hydrogen"

export interface CarDeal {
  id: string
  title: string
  description: string
  price: number
  discountedPrice?: number
  image: string
  category: CarDealCategory
  condition: CarCondition
  year: number
  make: string
  model: string
  mileage: number
  exteriorColor: string
  interiorColor: string
  fuelType: FuelType
  mpg: {
    city: number
    highway: number
  }
  engine: string
  transmission: TransmissionType
  drivetrain: DrivetrainType
  vin: string
  features: string[]
  safetyRating: number
  dealershipId: string
  financingAvailable: boolean
  leaseAvailable: boolean
  specialOffer?: string
  warrantyMonths: number
  isFeatured: boolean
  inStock: boolean
  stockCount?: number
  testDriveAvailable: boolean
  deliveryAvailable: boolean
  tradeInAccepted: boolean
  carfaxReportAvailable: boolean
  videoTourAvailable: boolean
  createdAt: string
}

export interface Dealership {
  id: string
  name: string
  logo: string
  description: string
  location: {
    address: string
    city: string
    state: string
    zipCode: string
    coordinates: {
      latitude: number
      longitude: number
    }
  }
  rating: number
  reviewCount: number
  categories: CarDealCategory[]
  yearsInBusiness: number
  certifications: string[]
  contactInfo: {
    phone: string
    email: string
    website: string
  }
  businessHours: {
    monday: string
    tuesday: string
    wednesday: string
    thursday: string
    friday: string
    saturday: string
    sunday: string
  }
  specialties: string[]
  financingOptions: string[]
  servicesOffered: string[]
  featured: boolean
}

export interface FinancingOption {
  id: string
  name: string
  description: string
  interestRate: number
  termMonths: number[]
  minimumDownPayment: number
  requiresCreditCheck: boolean
  availableForNewCars: boolean
  availableForUsedCars: boolean
  specialRequirements?: string
}

export const dealerships: Dealership[] = [
  {
    id: "dlr-001",
    name: "Premium Auto Gallery",
    logo: "/placeholder.svg?height=80&width=80",
    description: "Luxury car dealership specializing in high-end vehicles with exceptional customer service.",
    location: {
      address: "123 Luxury Lane",
      city: "Beverly Hills",
      state: "CA",
      zipCode: "90210",
      coordinates: {
        latitude: 34.0736,
        longitude: -118.4004,
      },
    },
    rating: 4.8,
    reviewCount: 342,
    categories: ["Luxury", "Sports", "Electric"],
    yearsInBusiness: 25,
    certifications: ["Certified Luxury Dealer", "Elite Customer Service"],
    contactInfo: {
      phone: "(310) 555-1234",
      email: "sales@premiumautogallery.com",
      website: "www.premiumautogallery.com",
    },
    businessHours: {
      monday: "9:00 AM - 7:00 PM",
      tuesday: "9:00 AM - 7:00 PM",
      wednesday: "9:00 AM - 7:00 PM",
      thursday: "9:00 AM - 7:00 PM",
      friday: "9:00 AM - 8:00 PM",
      saturday: "10:00 AM - 6:00 PM",
      sunday: "11:00 AM - 5:00 PM",
    },
    specialties: ["Exotic Cars", "Concierge Service", "Custom Orders"],
    financingOptions: ["Premium Financing", "Lease Specials", "VIP Membership"],
    servicesOffered: ["Valet Service", "Extended Warranty", "Vehicle Customization"],
    featured: true,
  },
  {
    id: "dlr-002",
    name: "EcoMotion Auto",
    logo: "/placeholder.svg?height=80&width=80",
    description: "Specializing in electric and hybrid vehicles with a focus on sustainability.",
    location: {
      address: "456 Green Drive",
      city: "Portland",
      state: "OR",
      zipCode: "97204",
      coordinates: {
        latitude: 45.5231,
        longitude: -122.6765,
      },
    },
    rating: 4.7,
    reviewCount: 289,
    categories: ["Electric", "Hybrid", "SUV"],
    yearsInBusiness: 12,
    certifications: ["Certified EV Specialist", "Green Dealership Award"],
    contactInfo: {
      phone: "(503) 555-6789",
      email: "info@ecomotion.com",
      website: "www.ecomotion.com",
    },
    businessHours: {
      monday: "8:00 AM - 6:00 PM",
      tuesday: "8:00 AM - 6:00 PM",
      wednesday: "8:00 AM - 6:00 PM",
      thursday: "8:00 AM - 6:00 PM",
      friday: "8:00 AM - 7:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "Closed",
    },
    specialties: ["EV Charging Installation", "Solar Integration", "Carbon Offset Programs"],
    financingOptions: ["Green Vehicle Loans", "Tax Credit Assistance", "Solar Bundle Deals"],
    servicesOffered: ["EV Education", "Battery Health Monitoring", "Charging Network Access"],
    featured: true,
  },
  {
    id: "dlr-003",
    name: "Family Auto Center",
    logo: "/placeholder.svg?height=80&width=80",
    description: "Family-owned dealership offering reliable vehicles for every budget with honest pricing.",
    location: {
      address: "789 Main Street",
      city: "Columbus",
      state: "OH",
      zipCode: "43215",
      coordinates: {
        latitude: 39.9612,
        longitude: -82.9988,
      },
    },
    rating: 4.5,
    reviewCount: 512,
    categories: ["Sedan", "SUV", "Minivan", "Truck"],
    yearsInBusiness: 35,
    certifications: ["Family Business Excellence", "Community Service Award"],
    contactInfo: {
      phone: "(614) 555-9012",
      email: "sales@familyautocenter.com",
      website: "www.familyautocenter.com",
    },
    businessHours: {
      monday: "9:00 AM - 8:00 PM",
      tuesday: "9:00 AM - 8:00 PM",
      wednesday: "9:00 AM - 8:00 PM",
      thursday: "9:00 AM - 8:00 PM",
      friday: "9:00 AM - 8:00 PM",
      saturday: "9:00 AM - 6:00 PM",
      sunday: "12:00 PM - 5:00 PM",
    },
    specialties: ["Family Vehicles", "First-Time Buyer Programs", "Trade-In Specialists"],
    financingOptions: ["Flexible Financing", "First-Time Buyer Specials", "Military Discounts"],
    servicesOffered: ["Service Department", "Courtesy Vehicles", "Children's Play Area"],
    featured: false,
  },
  {
    id: "dlr-004",
    name: "Classic Motors",
    logo: "/placeholder.svg?height=80&width=80",
    description: "Specializing in vintage and classic automobiles with restoration services.",
    location: {
      address: "321 Heritage Road",
      city: "Charleston",
      state: "SC",
      zipCode: "29401",
      coordinates: {
        latitude: 32.7765,
        longitude: -79.9311,
      },
    },
    rating: 4.9,
    reviewCount: 178,
    categories: ["Vintage", "Luxury", "Convertible"],
    yearsInBusiness: 40,
    certifications: ["Antique Automobile Club Certified", "Master Restoration Specialists"],
    contactInfo: {
      phone: "(843) 555-3456",
      email: "info@classicmotors.com",
      website: "www.classicmotors.com",
    },
    businessHours: {
      monday: "10:00 AM - 5:00 PM",
      tuesday: "10:00 AM - 5:00 PM",
      wednesday: "10:00 AM - 5:00 PM",
      thursday: "10:00 AM - 5:00 PM",
      friday: "10:00 AM - 5:00 PM",
      saturday: "10:00 AM - 4:00 PM",
      sunday: "By Appointment",
    },
    specialties: ["Restoration", "Classic Car Sourcing", "Collection Management"],
    financingOptions: ["Collector Financing", "Insurance Partnerships", "Consignment Services"],
    servicesOffered: ["Restoration Workshop", "Climate-Controlled Storage", "Appraisal Services"],
    featured: true,
  },
  {
    id: "dlr-005",
    name: "Performance Motors",
    logo: "/placeholder.svg?height=80&width=80",
    description: "High-performance and sports car dealership with track-ready vehicles and modifications.",
    location: {
      address: "555 Speed Avenue",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      coordinates: {
        latitude: 30.2672,
        longitude: -97.7431,
      },
    },
    rating: 4.6,
    reviewCount: 267,
    categories: ["Sports", "Luxury", "Convertible"],
    yearsInBusiness: 18,
    certifications: ["Performance Tuning Certified", "Track Safety Specialists"],
    contactInfo: {
      phone: "(512) 555-7890",
      email: "sales@performancemotors.com",
      website: "www.performancemotors.com",
    },
    businessHours: {
      monday: "9:00 AM - 7:00 PM",
      tuesday: "9:00 AM - 7:00 PM",
      wednesday: "9:00 AM - 7:00 PM",
      thursday: "9:00 AM - 7:00 PM",
      friday: "9:00 AM - 7:00 PM",
      saturday: "10:00 AM - 6:00 PM",
      sunday: "12:00 PM - 5:00 PM",
    },
    specialties: ["Performance Upgrades", "Track Day Events", "Driver Training"],
    financingOptions: ["Performance Vehicle Financing", "Upgrade Packages", "Track Membership Bundles"],
    servicesOffered: ["Performance Tuning", "Custom Exhaust Systems", "Track Preparation"],
    featured: false,
  },
]

export const financingOptions: FinancingOption[] = [
  {
    id: "fin-001",
    name: "Standard Auto Loan",
    description: "Traditional auto financing with competitive rates and flexible terms.",
    interestRate: 3.49,
    termMonths: [36, 48, 60, 72],
    minimumDownPayment: 10,
    requiresCreditCheck: true,
    availableForNewCars: true,
    availableForUsedCars: true,
  },
  {
    id: "fin-002",
    name: "Premium Lease",
    description: "Luxury vehicle leasing with low monthly payments and upgrade options.",
    interestRate: 2.99,
    termMonths: [24, 36, 48],
    minimumDownPayment: 15,
    requiresCreditCheck: true,
    availableForNewCars: true,
    availableForUsedCars: false,
  },
  {
    id: "fin-003",
    name: "First-Time Buyer Program",
    description: "Special financing options for first-time car buyers with limited credit history.",
    interestRate: 5.99,
    termMonths: [36, 48, 60],
    minimumDownPayment: 15,
    requiresCreditCheck: true,
    availableForNewCars: true,
    availableForUsedCars: true,
    specialRequirements: "Proof of income and residence",
  },
  {
    id: "fin-004",
    name: "Zero Down Payment",
    description: "No down payment required for qualified buyers with excellent credit.",
    interestRate: 4.49,
    termMonths: [48, 60, 72],
    minimumDownPayment: 0,
    requiresCreditCheck: true,
    availableForNewCars: true,
    availableForUsedCars: false,
    specialRequirements: "Credit score 720+",
  },
  {
    id: "fin-005",
    name: "Green Vehicle Incentive",
    description: "Special rates for electric and hybrid vehicles, including tax credit guidance.",
    interestRate: 2.49,
    termMonths: [36, 48, 60, 72],
    minimumDownPayment: 10,
    requiresCreditCheck: true,
    availableForNewCars: true,
    availableForUsedCars: true,
    specialRequirements: "Electric or hybrid vehicles only",
  },
]

export const carDeals: CarDeal[] = [
  {
    id: "car-001",
    title: "2023 Mercedes-Benz S-Class",
    description:
      "Luxury sedan with premium features and cutting-edge technology. Experience the pinnacle of automotive luxury with this flagship model featuring handcrafted materials and state-of-the-art driver assistance systems.",
    price: 110000,
    discountedPrice: 105500,
    image: "/placeholder.svg?height=300&width=500",
    category: "Luxury",
    condition: "New",
    year: 2023,
    make: "Mercedes-Benz",
    model: "S-Class",
    mileage: 15,
    exteriorColor: "Obsidian Black",
    interiorColor: "Macchiato Beige",
    fuelType: "Gasoline",
    mpg: {
      city: 22,
      highway: 30,
    },
    engine: "3.0L Inline-6 Turbo",
    transmission: "Automatic",
    drivetrain: "RWD",
    vin: "WDDUG8DB1MA456789",
    features: [
      "Burmester 4D Surround Sound",
      "MBUX Infotainment System",
      "Heated and Ventilated Seats",
      "Panoramic Sunroof",
      "Augmented Reality Navigation",
      "Driver Assistance Package",
      "Nappa Leather Upholstery",
      "Ambient Lighting with 64 Colors",
    ],
    safetyRating: 5,
    dealershipId: "dlr-001",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "Complimentary maintenance for 3 years",
    warrantyMonths: 48,
    isFeatured: true,
    inStock: true,
    stockCount: 3,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-05-15T10:30:00Z",
  },
  {
    id: "car-002",
    title: "2023 Tesla Model S Plaid",
    description:
      "High-performance electric sedan with incredible acceleration and long range. This revolutionary vehicle delivers supercar performance with zero emissions and cutting-edge autonomous driving capabilities.",
    price: 129990,
    image: "/placeholder.svg?height=300&width=500",
    category: "Electric",
    condition: "New",
    year: 2023,
    make: "Tesla",
    model: "Model S Plaid",
    mileage: 5,
    exteriorColor: "Pearl White",
    interiorColor: "Black",
    fuelType: "Electric",
    mpg: {
      city: 0,
      highway: 0,
    },
    engine: "Tri-Motor Electric",
    transmission: "Automatic",
    drivetrain: "AWD",
    vin: "5YJSA1E40MF123456",
    features: [
      "1,020 Horsepower",
      "0-60 mph in 1.99 seconds",
      "396 Mile Range",
      "17-inch Touchscreen",
      "Full Self-Driving Capability",
      "Glass Roof",
      "Premium Sound System",
      "Wireless Charging",
    ],
    safetyRating: 5,
    dealershipId: "dlr-002",
    financingAvailable: true,
    leaseAvailable: true,
    warrantyMonths: 48,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-06-02T14:15:00Z",
  },
  {
    id: "car-003",
    title: "2022 Honda CR-V Hybrid",
    description:
      "Efficient and spacious hybrid SUV perfect for families. Combining excellent fuel economy with versatile cargo space and advanced safety features for peace of mind on every journey.",
    price: 35400,
    discountedPrice: 33900,
    image: "/placeholder.svg?height=300&width=500",
    category: "Hybrid",
    condition: "New",
    year: 2022,
    make: "Honda",
    model: "CR-V Hybrid",
    mileage: 12,
    exteriorColor: "Radiant Red Metallic",
    interiorColor: "Gray",
    fuelType: "Hybrid",
    mpg: {
      city: 40,
      highway: 35,
    },
    engine: "2.0L 4-Cylinder Hybrid",
    transmission: "CVT",
    drivetrain: "AWD",
    vin: "7FARW2H90NE012345",
    features: [
      "Honda Sensing Safety Suite",
      "Apple CarPlay & Android Auto",
      "Heated Front Seats",
      "Power Tailgate",
      "Dual-Zone Climate Control",
      "Blind Spot Information System",
      "LED Headlights",
      "Wireless Phone Charger",
    ],
    safetyRating: 5,
    dealershipId: "dlr-003",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "$1,500 cash back",
    warrantyMonths: 36,
    isFeatured: false,
    inStock: true,
    stockCount: 5,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-04-10T09:45:00Z",
  },
  {
    id: "car-004",
    title: "1967 Ford Mustang Fastback",
    description:
      "Fully restored classic American muscle car. This iconic piece of automotive history has been meticulously restored to its original glory with period-correct details and modern reliability upgrades.",
    price: 89500,
    image: "/placeholder.svg?height=300&width=500",
    category: "Vintage",
    condition: "Used",
    year: 1967,
    make: "Ford",
    model: "Mustang Fastback",
    mileage: 1200,
    exteriorColor: "Highland Green",
    interiorColor: "Black",
    fuelType: "Gasoline",
    mpg: {
      city: 14,
      highway: 20,
    },
    engine: "390 V8",
    transmission: "Manual",
    drivetrain: "RWD",
    vin: "7R02C123456",
    features: [
      "Professionally Restored",
      "Numbers Matching Engine",
      "Deluxe Interior",
      "GT Equipment Group",
      "Power Steering",
      "Disc Brakes",
      "Vintage Air Conditioning",
      "Period-Correct Rally Wheels",
    ],
    safetyRating: 3,
    dealershipId: "dlr-004",
    financingAvailable: true,
    leaseAvailable: false,
    warrantyMonths: 12,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: false,
    tradeInAccepted: true,
    carfaxReportAvailable: false,
    videoTourAvailable: true,
    createdAt: "2023-03-20T11:30:00Z",
  },
  {
    id: "car-005",
    title: "2023 Porsche 911 GT3",
    description:
      "Track-focused sports car with exceptional handling and performance. Engineered for driving enthusiasts who demand the ultimate in precision, speed, and driving engagement on both road and track.",
    price: 169700,
    image: "/placeholder.svg?height=300&width=500",
    category: "Sports",
    condition: "New",
    year: 2023,
    make: "Porsche",
    model: "911 GT3",
    mileage: 25,
    exteriorColor: "Guards Red",
    interiorColor: "Black",
    fuelType: "Gasoline",
    mpg: {
      city: 14,
      highway: 18,
    },
    engine: "4.0L Flat-6",
    transmission: "Manual",
    drivetrain: "RWD",
    vin: "WP0AC2A93PS192837",
    features: [
      "502 Horsepower",
      "Carbon Fiber Components",
      "Sport Chrono Package",
      "Adaptive Sport Seats",
      "Track Precision App",
      "Ceramic Composite Brakes",
      "Sport Exhaust System",
      "Rear-Wheel Steering",
    ],
    safetyRating: 5,
    dealershipId: "dlr-005",
    financingAvailable: true,
    leaseAvailable: true,
    warrantyMonths: 48,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-05-05T16:20:00Z",
  },
  {
    id: "car-006",
    title: "2022 Toyota RAV4 Prime",
    description:
      "Plug-in hybrid SUV with excellent fuel economy and versatility. Offering the best of both worlds with electric-only driving capability for daily commutes and hybrid efficiency for longer journeys.",
    price: 42600,
    discountedPrice: 40900,
    image: "/placeholder.svg?height=300&width=500",
    category: "Hybrid",
    condition: "New",
    year: 2022,
    make: "Toyota",
    model: "RAV4 Prime",
    mileage: 8,
    exteriorColor: "Blueprint",
    interiorColor: "Black",
    fuelType: "Plug-in Hybrid",
    mpg: {
      city: 40,
      highway: 36,
    },
    engine: "2.5L 4-Cylinder Plug-in Hybrid",
    transmission: "CVT",
    drivetrain: "AWD",
    vin: "JTMEB3FV6ND123456",
    features: [
      "42-Mile Electric Range",
      "302 Combined Horsepower",
      "Toyota Safety Sense 2.0",
      "9-inch Touchscreen",
      "JBL Premium Audio",
      "Heated and Ventilated Seats",
      "Panoramic Glass Roof",
      "Wireless Smartphone Charging",
    ],
    safetyRating: 5,
    dealershipId: "dlr-002",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "Federal Tax Credit Eligible",
    warrantyMonths: 36,
    isFeatured: false,
    inStock: true,
    stockCount: 2,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-04-25T13:10:00Z",
  },
  {
    id: "car-007",
    title: "2021 Chevrolet Silverado 1500",
    description:
      "Powerful and capable full-size pickup truck for work and play. Built to handle tough jobs with impressive towing capacity, innovative cargo solutions, and comfortable interior amenities.",
    price: 45000,
    discountedPrice: 42500,
    image: "/placeholder.svg?height=300&width=500",
    category: "Truck",
    condition: "Used",
    year: 2021,
    make: "Chevrolet",
    model: "Silverado 1500",
    mileage: 15000,
    exteriorColor: "Silver Ice Metallic",
    interiorColor: "Jet Black",
    fuelType: "Gasoline",
    mpg: {
      city: 16,
      highway: 21,
    },
    engine: "5.3L V8",
    transmission: "Automatic",
    drivetrain: "4WD",
    vin: "3GCUYDED8MG123456",
    features: [
      "Multi-Flex Tailgate",
      "Trailering Package",
      "Z71 Off-Road Package",
      "Heated Seats and Steering Wheel",
      "8-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "Bose Premium Sound System",
      "Advanced Trailering System",
    ],
    safetyRating: 4,
    dealershipId: "dlr-003",
    financingAvailable: true,
    leaseAvailable: false,
    specialOffer: "$2,500 cash back",
    warrantyMonths: 24,
    isFeatured: false,
    inStock: true,
    stockCount: 3,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-02-15T10:00:00Z",
  },
  {
    id: "car-008",
    title: "2023 BMW M4 Competition",
    description:
      "High-performance luxury coupe with aggressive styling and exhilarating driving dynamics. Designed to deliver an adrenaline-pumping experience with track-capable performance and premium comfort.",
    price: 79000,
    image: "/placeholder.svg?height=300&width=500",
    category: "Sports",
    condition: "New",
    year: 2023,
    make: "BMW",
    model: "M4 Competition",
    mileage: 20,
    exteriorColor: "Isle of Man Green",
    interiorColor: "Kyalami Orange",
    fuelType: "Gasoline",
    mpg: {
      city: 16,
      highway: 23,
    },
    engine: "3.0L Twin-Turbo Inline-6",
    transmission: "Automatic",
    drivetrain: "RWD",
    vin: "WBS53AF08MCF12345",
    features: [
      "503 Horsepower",
      "Competition Package",
      "M Carbon Exterior Package",
      "Adaptive M Suspension",
      "M Drive Professional",
      "Harman Kardon Surround Sound",
      "Head-Up Display",
      "Carbon Fiber Interior Trim",
    ],
    safetyRating: 5,
    dealershipId: "dlr-005",
    financingAvailable: true,
    leaseAvailable: true,
    warrantyMonths: 48,
    isFeatured: true,
    inStock: true,
    stockCount: 2,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-05-12T15:45:00Z",
  },
  {
    id: "car-009",
    title: "2020 Audi Q7 Premium Plus",
    description:
      "Luxurious three-row SUV with advanced technology and refined comfort. Perfect for families seeking upscale amenities, safety features, and Audi's legendary Quattro all-wheel drive system.",
    price: 54900,
    discountedPrice: 51500,
    image: "/placeholder.svg?height=300&width=500",
    category: "SUV",
    condition: "Used",
    year: 2020,
    make: "Audi",
    model: "Q7 Premium Plus",
    mileage: 28500,
    exteriorColor: "Samurai Gray",
    interiorColor: "Black",
    fuelType: "Gasoline",
    mpg: {
      city: 19,
      highway: 23,
    },
    engine: "3.0L V6 Turbo",
    transmission: "Automatic",
    drivetrain: "AWD",
    vin: "WA1VAAF79LD012345",
    features: [
      "Quattro All-Wheel Drive",
      "Virtual Cockpit",
      "Bang & Olufsen 3D Sound",
      "Panoramic Sunroof",
      "Heated and Ventilated Seats",
      "Adaptive Cruise Control",
      "Lane Departure Warning",
      "360-Degree Camera System",
    ],
    safetyRating: 5,
    dealershipId: "dlr-001",
    financingAvailable: true,
    leaseAvailable: false,
    specialOffer: "Certified Pre-Owned Warranty",
    warrantyMonths: 24,
    isFeatured: false,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-03-05T09:20:00Z",
  },
  {
    id: "car-010",
    title: "1970 Dodge Challenger R/T",
    description:
      "Iconic American muscle car restored to showroom condition. This classic Mopar features its original big block engine and represents the golden era of American performance cars.",
    price: 125000,
    image: "/placeholder.svg?height=300&width=500",
    category: "Vintage",
    condition: "Used",
    year: 1970,
    make: "Dodge",
    model: "Challenger R/T",
    mileage: 850,
    exteriorColor: "Plum Crazy Purple",
    interiorColor: "White",
    fuelType: "Gasoline",
    mpg: {
      city: 10,
      highway: 14,
    },
    engine: "426 HEMI V8",
    transmission: "Manual",
    drivetrain: "RWD",
    vin: "JS23R0B123456",
    features: [
      "Numbers Matching Engine",
      "Shaker Hood",
      "Pistol Grip Shifter",
      "Rally Gauges",
      "Power Steering",
      "Power Brakes",
      "Original Build Sheet",
      "Concours Quality Restoration",
    ],
    safetyRating: 3,
    dealershipId: "dlr-004",
    financingAvailable: true,
    leaseAvailable: false,
    warrantyMonths: 6,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: false,
    tradeInAccepted: false,
    carfaxReportAvailable: false,
    videoTourAvailable: true,
    createdAt: "2023-04-18T14:30:00Z",
  },
  {
    id: "car-011",
    title: "2023 Rivian R1S",
    description:
      "All-electric luxury SUV with exceptional off-road capability. Combining cutting-edge technology with adventure-ready features for the modern outdoor enthusiast.",
    price: 84500,
    image: "/placeholder.svg?height=300&width=500",
    category: "Electric",
    condition: "New",
    year: 2023,
    make: "Rivian",
    model: "R1S",
    mileage: 10,
    exteriorColor: "Limestone",
    interiorColor: "Black Mountain",
    fuelType: "Electric",
    mpg: {
      city: 0,
      highway: 0,
    },
    engine: "Quad-Motor Electric",
    transmission: "Automatic",
    drivetrain: "AWD",
    vin: "7FTTW0123456789",
    features: [
      "835 Horsepower",
      "316 Mile Range",
      "0-60 mph in 3.0 seconds",
      "Adjustable Air Suspension",
      "Vegan Leather Interior",
      "Meridian Audio System",
      "Gear Tunnel Storage",
      "Adventure Package",
    ],
    safetyRating: 5,
    dealershipId: "dlr-002",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "Free Home Charger Installation",
    warrantyMonths: 60,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-06-01T11:00:00Z",
  },
  {
    id: "car-012",
    title: "2022 Mazda MX-5 Miata Club",
    description:
      "Lightweight, nimble roadster delivering pure driving enjoyment. The perfect balance of power, handling, and open-air freedom for driving enthusiasts.",
    price: 32500,
    discountedPrice: 30900,
    image: "/placeholder.svg?height=300&width=500",
    category: "Convertible",
    condition: "New",
    year: 2022,
    make: "Mazda",
    model: "MX-5 Miata Club",
    mileage: 5,
    exteriorColor: "Soul Red Crystal",
    interiorColor: "Black",
    fuelType: "Gasoline",
    mpg: {
      city: 26,
      highway: 34,
    },
    engine: "2.0L 4-Cylinder",
    transmission: "Manual",
    drivetrain: "RWD",
    vin: "JM1NDAD78N0123456",
    features: [
      "Brembo Brakes",
      "Bilstein Dampers",
      "Limited-Slip Differential",
      "Bose Audio System",
      "Apple CarPlay & Android Auto",
      "Heated Seats",
      "Blind Spot Monitoring",
      "Soft Top with Glass Rear Window",
    ],
    safetyRating: 4,
    dealershipId: "dlr-005",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "0.9% APR Financing",
    warrantyMonths: 36,
    isFeatured: false,
    inStock: true,
    stockCount: 2,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-03-25T13:40:00Z",
  },
  {
    id: "car-013",
    title: "2023 Genesis GV80",
    description:
      "Sophisticated luxury SUV with distinctive styling and premium features. Offering exceptional value in the luxury segment with refined comfort and advanced technology.",
    price: 65000,
    discountedPrice: 62500,
    image: "/placeholder.svg?height=300&width=500",
    category: "SUV",
    condition: "New",
    year: 2023,
    make: "Genesis",
    model: "GV80",
    mileage: 12,
    exteriorColor: "Cardiff Green",
    interiorColor: "Vanilla Beige",
    fuelType: "Gasoline",
    mpg: {
      city: 20,
      highway: 24,
    },
    engine: "3.5L V6 Twin-Turbo",
    transmission: "Automatic",
    drivetrain: "AWD",
    vin: "KMTG34LA8NU123456",
    features: [
      "14.5-inch Touchscreen",
      "Lexicon Premium Audio",
      "Ergo Motion Driver's Seat",
      "Remote Smart Parking Assist",
      "Highway Driving Assist II",
      "3D Digital Instrument Cluster",
      "Quilted Nappa Leather",
      "Panoramic Sunroof",
    ],
    safetyRating: 5,
    dealershipId: "dlr-001",
    financingAvailable: true,
    leaseAvailable: true,
    specialOffer: "Complimentary maintenance for 3 years",
    warrantyMonths: 60,
    isFeatured: false,
    inStock: true,
    stockCount: 2,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-05-20T10:15:00Z",
  },
  {
    id: "car-014",
    title: "2021 Volkswagen ID.4 Pro S",
    description:
      "All-electric compact SUV with impressive range and spacious interior. Combining German engineering with zero-emission driving for a sustainable and practical daily driver.",
    price: 45500,
    discountedPrice: 43000,
    image: "/placeholder.svg?height=300&width=500",
    category: "Electric",
    condition: "Used",
    year: 2021,
    make: "Volkswagen",
    model: "ID.4 Pro S",
    mileage: 18500,
    exteriorColor: "Moonstone Gray",
    interiorColor: "Galaxy Black",
    fuelType: "Electric",
    mpg: {
      city: 0,
      highway: 0,
    },
    engine: "Single-Motor Electric",
    transmission: "Automatic",
    drivetrain: "RWD",
    vin: "1VWBA7A39MC123456",
    features: [
      "250-Mile Range",
      "12-inch Touchscreen",
      "ID. Light Interactive System",
      "Panoramic Fixed Glass Roof",
      "Massage Front Seats",
      "Travel Assist",
      "Wireless App-Connect",
      "Hands-Free Easy Open Liftgate",
    ],
    safetyRating: 5,
    dealershipId: "dlr-002",
    financingAvailable: true,
    leaseAvailable: false,
    specialOffer: "Remaining Factory Warranty",
    warrantyMonths: 24,
    isFeatured: false,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: false,
    createdAt: "2023-04-05T16:30:00Z",
  },
  {
    id: "car-015",
    title: "2023 Cadillac Escalade ESV",
    description:
      "Full-size luxury SUV with extended length and premium appointments. The ultimate expression of American luxury with imposing presence and state-of-the-art technology.",
    price: 110000,
    image: "/placeholder.svg?height=300&width=500",
    category: "SUV",
    condition: "New",
    year: 2023,
    make: "Cadillac",
    model: "Escalade ESV",
    mileage: 15,
    exteriorColor: "Dark Moon Blue Metallic",
    interiorColor: "Whisper Beige",
    fuelType: "Gasoline",
    mpg: {
      city: 14,
      highway: 19,
    },
    engine: "6.2L V8",
    transmission: "Automatic",
    drivetrain: "4WD",
    vin: "1GYS4KKL8PR123456",
    features: [
      "38-inch Curved OLED Display",
      "AKG Studio Reference 36-Speaker Audio",
      "Super Cruise Hands-Free Driving",
      "Night Vision",
      "Rear Seat Entertainment System",
      "Magnetic Ride Control",
      "Air Ride Adaptive Suspension",
      "Refrigerated Center Console",
    ],
    safetyRating: 5,
    dealershipId: "dlr-001",
    financingAvailable: true,
    leaseAvailable: true,
    warrantyMonths: 48,
    isFeatured: true,
    inStock: true,
    stockCount: 1,
    testDriveAvailable: true,
    deliveryAvailable: true,
    tradeInAccepted: true,
    carfaxReportAvailable: true,
    videoTourAvailable: true,
    createdAt: "2023-05-28T12:00:00Z",
  },
]

export const categories: CarDealCategory[] = [
  "Luxury",
  "SUV",
  "Sedan",
  "Electric",
  "Hybrid",
  "Sports",
  "Vintage",
  "Truck",
  "Convertible",
  "Minivan",
]

export const conditions: CarCondition[] = ["New", "Used", "Certified Pre-Owned"]

export const fuelTypes: FuelType[] = ["Gasoline", "Diesel", "Electric", "Hybrid", "Plug-in Hybrid", "Hydrogen"]

