import type { ProductRanking } from "@/components/TrendingPopularSection"

// Mock data for trending products in retail and supermarket
export const trendingProducts: ProductRanking[] = [
  {
    id: "tr1",
    name: "Organic Avocados (Pack of 4)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 5.99,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Fruits",
    vendor: "Kagio Market",
    rank: 1,
    url: "/retail-and-supermarket/shop/products/organic-avocados",
    badges: ["trending", "hot"],
  },
  {
    id: "tr2",
    name: "Fresh Farm Eggs (Tray of 30)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 7.5,
      currency: "KSh",
    },
    rating: 4.7,
    category: "Dairy & Eggs",
    vendor: "Nakuru Farms",
    rank: 2,
    url: "/retail-and-supermarket/shop/products/farm-eggs",
    badges: ["trending"],
  },
  {
    id: "tr3",
    name: "Premium Kenyan Coffee Beans",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 12.99,
      currency: "KSh",
    },
    rating: 4.9,
    category: "Beverages",
    vendor: "Mount Kenya Coffee",
    rank: 3,
    url: "/retail-and-supermarket/shop/products/kenyan-coffee",
    badges: ["trending", "popular"],
  },
  {
    id: "tr4",
    name: "Fresh Tilapia Fish (1kg)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 8.75,
      currency: "KSh",
    },
    rating: 4.6,
    category: "Seafood",
    vendor: "Lake Victoria Fisheries",
    rank: 4,
    url: "/retail-and-supermarket/shop/products/tilapia-fish",
    badges: ["trending"],
  },
  {
    id: "tr5",
    name: "Organic Baby Spinach (500g)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 3.49,
      currency: "KSh",
    },
    rating: 4.5,
    category: "Vegetables",
    vendor: "Kagio Market",
    rank: 5,
    url: "/retail-and-supermarket/shop/products/baby-spinach",
    badges: ["trending", "new"],
  },
]

// Mock data for most popular products in retail and supermarket
export const popularProducts: ProductRanking[] = [
  {
    id: "pop1",
    name: "Maasai Honey (500ml)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 9.99,
      currency: "KSh",
    },
    rating: 4.9,
    category: "Condiments",
    vendor: "Maasai Beekeepers",
    rank: 1,
    url: "/retail-and-supermarket/shop/products/maasai-honey",
    badges: ["popular", "hot"],
  },
  {
    id: "pop2",
    name: "Grass-Fed Beef Steak (500g)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 15.5,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Meat",
    vendor: "Narok Ranchers",
    rank: 2,
    url: "/retail-and-supermarket/shop/products/beef-steak",
    badges: ["popular"],
  },
  {
    id: "pop3",
    name: "Organic Bananas (Bunch)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 2.99,
      currency: "KSh",
    },
    rating: 4.7,
    category: "Fruits",
    vendor: "Kagio Market",
    rank: 3,
    url: "/retail-and-supermarket/shop/products/organic-bananas",
    badges: ["popular", "trending"],
  },
  {
    id: "pop4",
    name: "Fresh Milk (2L)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 4.25,
      currency: "KSh",
    },
    rating: 4.6,
    category: "Dairy & Eggs",
    vendor: "Kiambu Dairy",
    rank: 4,
    url: "/retail-and-supermarket/shop/products/fresh-milk",
    badges: ["popular"],
  },
  {
    id: "pop5",
    name: "Chapati Flour (2kg)",
    image: "/placeholder.svg?height=400&width=400",
    price: {
      amount: 5.75,
      currency: "KSh",
    },
    rating: 4.8,
    category: "Baking & Cooking",
    vendor: "Unga Limited",
    rank: 5,
    url: "/retail-and-supermarket/shop/products/chapati-flour",
    badges: ["popular", "hot"],
  },
]

